// Code generated by plangen.

// Copyright 2025 Dolthub, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package queries

import (
	"github.com/dolthub/go-mysql-server/sql"
)

var QueryPlanScriptTests = []ScriptTest{
	{
		Name: "test merge join optimization (removing sort node over indexed tables) does not break ordering",
		SetUpScript: []string{
			`create table t1 (i int primary key);`,
			`create table t2 (j int primary key);`,
			`insert into t1 values (1), (2), (3);`,
			`insert into t2 values (2), (3), (4);`,
			`create table t3 (i int, j int, primary key (i, j));`,
			`create table t4 (x int, y int, primary key (x, y));`,
			`insert into t3 values (1, 1), (1, 2), (2, 2), (3, 3);`,
			`insert into t4 values (2, 2), (3, 3), (4, 4);`,
		},
		Assertions: []ScriptTestAssertion{
			{
				Query: `select /*+ MERGE_JOIN(t1, t2) */ * from t1 join t2 on t1.i = t2.j order by t1.i;`,
				Expected: []sql.Row{
					sql.Row{2, 2},
					sql.Row{3, 3},
				},
				ExpectedPlan: "MergeJoin\n" +
					" ├─ cmp: Eq\n" +
					" │   ├─ t1.i:0!null\n" +
					" │   └─ t2.j:1!null\n" +
					" ├─ IndexedTableAccess(t1)\n" +
					" │   ├─ index: [t1.i]\n" +
					" │   ├─ static: [{[NULL, ∞)}]\n" +
					" │   ├─ colSet: (1)\n" +
					" │   ├─ tableId: 1\n" +
					" │   └─ Table\n" +
					" │       ├─ name: t1\n" +
					" │       └─ columns: [i]\n" +
					" └─ IndexedTableAccess(t2)\n" +
					"     ├─ index: [t2.j]\n" +
					"     ├─ static: [{[NULL, ∞)}]\n" +
					"     ├─ colSet: (2)\n" +
					"     ├─ tableId: 2\n" +
					"     └─ Table\n" +
					"         ├─ name: t2\n" +
					"         └─ columns: [j]\n" +
					"",
			},
			{
				Query: `select /*+ MERGE_JOIN(t1, t2) */ * from t1 join t2 on t1.i = t2.j order by t2.j;`,
				Expected: []sql.Row{
					sql.Row{2, 2},
					sql.Row{3, 3},
				},
				ExpectedPlan: "MergeJoin\n" +
					" ├─ cmp: Eq\n" +
					" │   ├─ t1.i:0!null\n" +
					" │   └─ t2.j:1!null\n" +
					" ├─ IndexedTableAccess(t1)\n" +
					" │   ├─ index: [t1.i]\n" +
					" │   ├─ static: [{[NULL, ∞)}]\n" +
					" │   ├─ colSet: (1)\n" +
					" │   ├─ tableId: 1\n" +
					" │   └─ Table\n" +
					" │       ├─ name: t1\n" +
					" │       └─ columns: [i]\n" +
					" └─ IndexedTableAccess(t2)\n" +
					"     ├─ index: [t2.j]\n" +
					"     ├─ static: [{[NULL, ∞)}]\n" +
					"     ├─ colSet: (2)\n" +
					"     ├─ tableId: 2\n" +
					"     └─ Table\n" +
					"         ├─ name: t2\n" +
					"         └─ columns: [j]\n" +
					"",
			},
			{
				Query: `select /*+ MERGE_JOIN(t1, t2) */ * from t1 join t2 on t1.i = t2.j order by t1.i desc;`,
				Expected: []sql.Row{
					sql.Row{3, 3},
					sql.Row{2, 2},
				},
				ExpectedPlan: "MergeJoin\n" +
					" ├─ cmp: Eq\n" +
					" │   ├─ t1.i:0!null\n" +
					" │   └─ t2.j:1!null\n" +
					" ├─ IndexedTableAccess(t1)\n" +
					" │   ├─ index: [t1.i]\n" +
					" │   ├─ static: [{[NULL, ∞)}]\n" +
					" │   ├─ reverse: true\n" +
					" │   ├─ colSet: (1)\n" +
					" │   ├─ tableId: 1\n" +
					" │   └─ Table\n" +
					" │       ├─ name: t1\n" +
					" │       └─ columns: [i]\n" +
					" └─ IndexedTableAccess(t2)\n" +
					"     ├─ index: [t2.j]\n" +
					"     ├─ static: [{[NULL, ∞)}]\n" +
					"     ├─ reverse: true\n" +
					"     ├─ colSet: (2)\n" +
					"     ├─ tableId: 2\n" +
					"     └─ Table\n" +
					"         ├─ name: t2\n" +
					"         └─ columns: [j]\n" +
					"",
			},
			{
				Query: `select /*+ MERGE_JOIN(t1, t2) */ * from t1 join t2 on t1.i = t2.j order by t2.j desc;`,
				Expected: []sql.Row{
					sql.Row{3, 3},
					sql.Row{2, 2},
				},
				ExpectedPlan: "MergeJoin\n" +
					" ├─ cmp: Eq\n" +
					" │   ├─ t1.i:0!null\n" +
					" │   └─ t2.j:1!null\n" +
					" ├─ IndexedTableAccess(t1)\n" +
					" │   ├─ index: [t1.i]\n" +
					" │   ├─ static: [{[NULL, ∞)}]\n" +
					" │   ├─ reverse: true\n" +
					" │   ├─ colSet: (1)\n" +
					" │   ├─ tableId: 1\n" +
					" │   └─ Table\n" +
					" │       ├─ name: t1\n" +
					" │       └─ columns: [i]\n" +
					" └─ IndexedTableAccess(t2)\n" +
					"     ├─ index: [t2.j]\n" +
					"     ├─ static: [{[NULL, ∞)}]\n" +
					"     ├─ reverse: true\n" +
					"     ├─ colSet: (2)\n" +
					"     ├─ tableId: 2\n" +
					"     └─ Table\n" +
					"         ├─ name: t2\n" +
					"         └─ columns: [j]\n" +
					"",
			},
			{
				Query: `select /*+ MERGE_JOIN(t1, t2) */ * from t1 where ((i in (select j from t2 where j > 2))) order by i desc;`,
				Expected: []sql.Row{
					sql.Row{3},
				},
				ExpectedPlan: "Project\n" +
					" ├─ columns: [t1.i:0!null]\n" +
					" └─ MergeJoin\n" +
					"     ├─ cmp: Eq\n" +
					"     │   ├─ t1.i:0!null\n" +
					"     │   └─ t2.j:1!null\n" +
					"     ├─ IndexedTableAccess(t1)\n" +
					"     │   ├─ index: [t1.i]\n" +
					"     │   ├─ static: [{[NULL, ∞)}]\n" +
					"     │   ├─ reverse: true\n" +
					"     │   ├─ colSet: (1)\n" +
					"     │   ├─ tableId: 1\n" +
					"     │   └─ Table\n" +
					"     │       ├─ name: t1\n" +
					"     │       └─ columns: [i]\n" +
					"     └─ Distinct\n" +
					"         └─ Filter\n" +
					"             ├─ GreaterThan\n" +
					"             │   ├─ t2.j:0!null\n" +
					"             │   └─ 2 (int)\n" +
					"             └─ IndexedTableAccess(t2)\n" +
					"                 ├─ index: [t2.j]\n" +
					"                 ├─ static: [{[NULL, ∞)}]\n" +
					"                 ├─ reverse: true\n" +
					"                 ├─ colSet: (2)\n" +
					"                 ├─ tableId: 2\n" +
					"                 └─ Table\n" +
					"                     ├─ name: t2\n" +
					"                     └─ columns: [j]\n" +
					"",
			},
			{
				Query: `select /*+ MERGE_JOIN(t3, t4) */ * from t3 join t4 on t3.i = t4.x order by t3.i;`,
				Expected: []sql.Row{
					sql.Row{2, 2, 2, 2},
					sql.Row{3, 3, 3, 3},
				},
				ExpectedPlan: "MergeJoin\n" +
					" ├─ cmp: Eq\n" +
					" │   ├─ t3.i:0!null\n" +
					" │   └─ t4.x:2!null\n" +
					" ├─ IndexedTableAccess(t3)\n" +
					" │   ├─ index: [t3.i,t3.j]\n" +
					" │   ├─ static: [{[NULL, ∞), [NULL, ∞)}]\n" +
					" │   ├─ colSet: (1,2)\n" +
					" │   ├─ tableId: 1\n" +
					" │   └─ Table\n" +
					" │       ├─ name: t3\n" +
					" │       └─ columns: [i j]\n" +
					" └─ IndexedTableAccess(t4)\n" +
					"     ├─ index: [t4.x,t4.y]\n" +
					"     ├─ static: [{[NULL, ∞), [NULL, ∞)}]\n" +
					"     ├─ colSet: (3,4)\n" +
					"     ├─ tableId: 2\n" +
					"     └─ Table\n" +
					"         ├─ name: t4\n" +
					"         └─ columns: [x y]\n" +
					"",
			},
			{
				Query: `select /*+ MERGE_JOIN(t3, t4) */ * from t3 join t4 on t3.i = t4.x order by t3.i desc;`,
				Expected: []sql.Row{
					sql.Row{3, 3, 3, 3},
					sql.Row{2, 2, 2, 2},
				},
				ExpectedPlan: "MergeJoin\n" +
					" ├─ cmp: Eq\n" +
					" │   ├─ t3.i:0!null\n" +
					" │   └─ t4.x:2!null\n" +
					" ├─ IndexedTableAccess(t3)\n" +
					" │   ├─ index: [t3.i,t3.j]\n" +
					" │   ├─ static: [{[NULL, ∞), [NULL, ∞)}]\n" +
					" │   ├─ reverse: true\n" +
					" │   ├─ colSet: (1,2)\n" +
					" │   ├─ tableId: 1\n" +
					" │   └─ Table\n" +
					" │       ├─ name: t3\n" +
					" │       └─ columns: [i j]\n" +
					" └─ IndexedTableAccess(t4)\n" +
					"     ├─ index: [t4.x,t4.y]\n" +
					"     ├─ static: [{[NULL, ∞), [NULL, ∞)}]\n" +
					"     ├─ reverse: true\n" +
					"     ├─ colSet: (3,4)\n" +
					"     ├─ tableId: 2\n" +
					"     └─ Table\n" +
					"         ├─ name: t4\n" +
					"         └─ columns: [x y]\n" +
					"",
			},
			{
				Query: `select /*+ MERGE_JOIN(t3, t4) */ * from t3 join t4 on t3.i = t4.x order by t4.x;`,
				Expected: []sql.Row{
					sql.Row{2, 2, 2, 2},
					sql.Row{3, 3, 3, 3},
				},
				ExpectedPlan: "MergeJoin\n" +
					" ├─ cmp: Eq\n" +
					" │   ├─ t3.i:0!null\n" +
					" │   └─ t4.x:2!null\n" +
					" ├─ IndexedTableAccess(t3)\n" +
					" │   ├─ index: [t3.i,t3.j]\n" +
					" │   ├─ static: [{[NULL, ∞), [NULL, ∞)}]\n" +
					" │   ├─ colSet: (1,2)\n" +
					" │   ├─ tableId: 1\n" +
					" │   └─ Table\n" +
					" │       ├─ name: t3\n" +
					" │       └─ columns: [i j]\n" +
					" └─ IndexedTableAccess(t4)\n" +
					"     ├─ index: [t4.x,t4.y]\n" +
					"     ├─ static: [{[NULL, ∞), [NULL, ∞)}]\n" +
					"     ├─ colSet: (3,4)\n" +
					"     ├─ tableId: 2\n" +
					"     └─ Table\n" +
					"         ├─ name: t4\n" +
					"         └─ columns: [x y]\n" +
					"",
			},
			{
				Query: `select /*+ MERGE_JOIN(t3, t4) */ * from t3 join t4 on t3.i = t4.x order by t4.x desc;`,
				Expected: []sql.Row{
					sql.Row{3, 3, 3, 3},
					sql.Row{2, 2, 2, 2},
				},
				ExpectedPlan: "MergeJoin\n" +
					" ├─ cmp: Eq\n" +
					" │   ├─ t3.i:0!null\n" +
					" │   └─ t4.x:2!null\n" +
					" ├─ IndexedTableAccess(t3)\n" +
					" │   ├─ index: [t3.i,t3.j]\n" +
					" │   ├─ static: [{[NULL, ∞), [NULL, ∞)}]\n" +
					" │   ├─ reverse: true\n" +
					" │   ├─ colSet: (1,2)\n" +
					" │   ├─ tableId: 1\n" +
					" │   └─ Table\n" +
					" │       ├─ name: t3\n" +
					" │       └─ columns: [i j]\n" +
					" └─ IndexedTableAccess(t4)\n" +
					"     ├─ index: [t4.x,t4.y]\n" +
					"     ├─ static: [{[NULL, ∞), [NULL, ∞)}]\n" +
					"     ├─ reverse: true\n" +
					"     ├─ colSet: (3,4)\n" +
					"     ├─ tableId: 2\n" +
					"     └─ Table\n" +
					"         ├─ name: t4\n" +
					"         └─ columns: [x y]\n" +
					"",
			},
			{
				Query: `select /*+ MERGE_JOIN(t3, t4) */ * from t3 join t4 on t3.i = t4.x order by t3.i, t3.j;`,
				Expected: []sql.Row{
					sql.Row{2, 2, 2, 2},
					sql.Row{3, 3, 3, 3},
				},
				ExpectedPlan: "MergeJoin\n" +
					" ├─ cmp: Eq\n" +
					" │   ├─ t3.i:0!null\n" +
					" │   └─ t4.x:2!null\n" +
					" ├─ IndexedTableAccess(t3)\n" +
					" │   ├─ index: [t3.i,t3.j]\n" +
					" │   ├─ static: [{[NULL, ∞), [NULL, ∞)}]\n" +
					" │   ├─ colSet: (1,2)\n" +
					" │   ├─ tableId: 1\n" +
					" │   └─ Table\n" +
					" │       ├─ name: t3\n" +
					" │       └─ columns: [i j]\n" +
					" └─ IndexedTableAccess(t4)\n" +
					"     ├─ index: [t4.x,t4.y]\n" +
					"     ├─ static: [{[NULL, ∞), [NULL, ∞)}]\n" +
					"     ├─ colSet: (3,4)\n" +
					"     ├─ tableId: 2\n" +
					"     └─ Table\n" +
					"         ├─ name: t4\n" +
					"         └─ columns: [x y]\n" +
					"",
			},
			{
				Query: `select /*+ MERGE_JOIN(t3, t4) */ * from t3 join t4 on t3.i = t4.x order by t3.i desc, t3.j desc;`,
				Expected: []sql.Row{
					sql.Row{3, 3, 3, 3},
					sql.Row{2, 2, 2, 2},
				},
				ExpectedPlan: "MergeJoin\n" +
					" ├─ cmp: Eq\n" +
					" │   ├─ t3.i:0!null\n" +
					" │   └─ t4.x:2!null\n" +
					" ├─ IndexedTableAccess(t3)\n" +
					" │   ├─ index: [t3.i,t3.j]\n" +
					" │   ├─ static: [{[NULL, ∞), [NULL, ∞)}]\n" +
					" │   ├─ reverse: true\n" +
					" │   ├─ colSet: (1,2)\n" +
					" │   ├─ tableId: 1\n" +
					" │   └─ Table\n" +
					" │       ├─ name: t3\n" +
					" │       └─ columns: [i j]\n" +
					" └─ IndexedTableAccess(t4)\n" +
					"     ├─ index: [t4.x,t4.y]\n" +
					"     ├─ static: [{[NULL, ∞), [NULL, ∞)}]\n" +
					"     ├─ reverse: true\n" +
					"     ├─ colSet: (3,4)\n" +
					"     ├─ tableId: 2\n" +
					"     └─ Table\n" +
					"         ├─ name: t4\n" +
					"         └─ columns: [x y]\n" +
					"",
			},
			{
				Query: `select /*+ MERGE_JOIN(t3, t4) */ * from t3 join t4 on t3.i = t4.x order by t4.x, t4.y;`,
				Expected: []sql.Row{
					sql.Row{2, 2, 2, 2},
					sql.Row{3, 3, 3, 3},
				},
				ExpectedPlan: "MergeJoin\n" +
					" ├─ cmp: Eq\n" +
					" │   ├─ t3.i:0!null\n" +
					" │   └─ t4.x:2!null\n" +
					" ├─ IndexedTableAccess(t3)\n" +
					" │   ├─ index: [t3.i,t3.j]\n" +
					" │   ├─ static: [{[NULL, ∞), [NULL, ∞)}]\n" +
					" │   ├─ colSet: (1,2)\n" +
					" │   ├─ tableId: 1\n" +
					" │   └─ Table\n" +
					" │       ├─ name: t3\n" +
					" │       └─ columns: [i j]\n" +
					" └─ IndexedTableAccess(t4)\n" +
					"     ├─ index: [t4.x,t4.y]\n" +
					"     ├─ static: [{[NULL, ∞), [NULL, ∞)}]\n" +
					"     ├─ colSet: (3,4)\n" +
					"     ├─ tableId: 2\n" +
					"     └─ Table\n" +
					"         ├─ name: t4\n" +
					"         └─ columns: [x y]\n" +
					"",
			},
			{
				Query: `select /*+ MERGE_JOIN(t3, t4) */ * from t3 join t4 on t3.i = t4.x order by t4.x desc, t4.y desc;`,
				Expected: []sql.Row{
					sql.Row{3, 3, 3, 3},
					sql.Row{2, 2, 2, 2},
				},
				ExpectedPlan: "MergeJoin\n" +
					" ├─ cmp: Eq\n" +
					" │   ├─ t3.i:0!null\n" +
					" │   └─ t4.x:2!null\n" +
					" ├─ IndexedTableAccess(t3)\n" +
					" │   ├─ index: [t3.i,t3.j]\n" +
					" │   ├─ static: [{[NULL, ∞), [NULL, ∞)}]\n" +
					" │   ├─ reverse: true\n" +
					" │   ├─ colSet: (1,2)\n" +
					" │   ├─ tableId: 1\n" +
					" │   └─ Table\n" +
					" │       ├─ name: t3\n" +
					" │       └─ columns: [i j]\n" +
					" └─ IndexedTableAccess(t4)\n" +
					"     ├─ index: [t4.x,t4.y]\n" +
					"     ├─ static: [{[NULL, ∞), [NULL, ∞)}]\n" +
					"     ├─ reverse: true\n" +
					"     ├─ colSet: (3,4)\n" +
					"     ├─ tableId: 2\n" +
					"     └─ Table\n" +
					"         ├─ name: t4\n" +
					"         └─ columns: [x y]\n" +
					"",
			},
			{
				Query: `select /*+ MERGE_JOIN(t3, t4) */ * from t3 join t4 on t3.i = t4.x order by t3.i, t4.x;`,
				Expected: []sql.Row{
					sql.Row{2, 2, 2, 2},
					sql.Row{3, 3, 3, 3},
				},
				ExpectedPlan: "Sort(t3.i:0!null ASC nullsFirst, t4.x:2!null ASC nullsFirst)\n" +
					" └─ MergeJoin\n" +
					"     ├─ cmp: Eq\n" +
					"     │   ├─ t3.i:0!null\n" +
					"     │   └─ t4.x:2!null\n" +
					"     ├─ IndexedTableAccess(t3)\n" +
					"     │   ├─ index: [t3.i,t3.j]\n" +
					"     │   ├─ static: [{[NULL, ∞), [NULL, ∞)}]\n" +
					"     │   ├─ colSet: (1,2)\n" +
					"     │   ├─ tableId: 1\n" +
					"     │   └─ Table\n" +
					"     │       ├─ name: t3\n" +
					"     │       └─ columns: [i j]\n" +
					"     └─ IndexedTableAccess(t4)\n" +
					"         ├─ index: [t4.x,t4.y]\n" +
					"         ├─ static: [{[NULL, ∞), [NULL, ∞)}]\n" +
					"         ├─ colSet: (3,4)\n" +
					"         ├─ tableId: 2\n" +
					"         └─ Table\n" +
					"             ├─ name: t4\n" +
					"             └─ columns: [x y]\n" +
					"",
			},
			{
				Query: `select /*+ MERGE_JOIN(t3, t4) */ * from t3 join t4 on t3.i = t4.x order by t3.i, t4.x desc;`,
				Expected: []sql.Row{
					sql.Row{2, 2, 2, 2},
					sql.Row{3, 3, 3, 3},
				},
				ExpectedPlan: "Sort(t3.i:0!null ASC nullsFirst, t4.x:2!null DESC nullsFirst)\n" +
					" └─ MergeJoin\n" +
					"     ├─ cmp: Eq\n" +
					"     │   ├─ t3.i:0!null\n" +
					"     │   └─ t4.x:2!null\n" +
					"     ├─ IndexedTableAccess(t3)\n" +
					"     │   ├─ index: [t3.i,t3.j]\n" +
					"     │   ├─ static: [{[NULL, ∞), [NULL, ∞)}]\n" +
					"     │   ├─ colSet: (1,2)\n" +
					"     │   ├─ tableId: 1\n" +
					"     │   └─ Table\n" +
					"     │       ├─ name: t3\n" +
					"     │       └─ columns: [i j]\n" +
					"     └─ IndexedTableAccess(t4)\n" +
					"         ├─ index: [t4.x,t4.y]\n" +
					"         ├─ static: [{[NULL, ∞), [NULL, ∞)}]\n" +
					"         ├─ colSet: (3,4)\n" +
					"         ├─ tableId: 2\n" +
					"         └─ Table\n" +
					"             ├─ name: t4\n" +
					"             └─ columns: [x y]\n" +
					"",
			},
			{
				Query: `select /*+ MERGE_JOIN(t3, t4) */ * from t3 join t4 on t3.i = t4.x order by t3.i, t3.j, t4.x;`,
				Expected: []sql.Row{
					sql.Row{2, 2, 2, 2},
					sql.Row{3, 3, 3, 3},
				},
				ExpectedPlan: "Sort(t3.i:0!null ASC nullsFirst, t3.j:1!null ASC nullsFirst, t4.x:2!null ASC nullsFirst)\n" +
					" └─ MergeJoin\n" +
					"     ├─ cmp: Eq\n" +
					"     │   ├─ t3.i:0!null\n" +
					"     │   └─ t4.x:2!null\n" +
					"     ├─ IndexedTableAccess(t3)\n" +
					"     │   ├─ index: [t3.i,t3.j]\n" +
					"     │   ├─ static: [{[NULL, ∞), [NULL, ∞)}]\n" +
					"     │   ├─ colSet: (1,2)\n" +
					"     │   ├─ tableId: 1\n" +
					"     │   └─ Table\n" +
					"     │       ├─ name: t3\n" +
					"     │       └─ columns: [i j]\n" +
					"     └─ IndexedTableAccess(t4)\n" +
					"         ├─ index: [t4.x,t4.y]\n" +
					"         ├─ static: [{[NULL, ∞), [NULL, ∞)}]\n" +
					"         ├─ colSet: (3,4)\n" +
					"         ├─ tableId: 2\n" +
					"         └─ Table\n" +
					"             ├─ name: t4\n" +
					"             └─ columns: [x y]\n" +
					"",
			},
			{
				Query: `select /*+ MERGE_JOIN(t3, t4) */ * from t3 join t4 on t3.i = t4.x order by t3.i, t3.j, t4.x, t4.y;`,
				Expected: []sql.Row{
					sql.Row{2, 2, 2, 2},
					sql.Row{3, 3, 3, 3},
				},
				ExpectedPlan: "Sort(t3.i:0!null ASC nullsFirst, t3.j:1!null ASC nullsFirst, t4.x:2!null ASC nullsFirst, t4.y:3!null ASC nullsFirst)\n" +
					" └─ MergeJoin\n" +
					"     ├─ cmp: Eq\n" +
					"     │   ├─ t3.i:0!null\n" +
					"     │   └─ t4.x:2!null\n" +
					"     ├─ IndexedTableAccess(t3)\n" +
					"     │   ├─ index: [t3.i,t3.j]\n" +
					"     │   ├─ static: [{[NULL, ∞), [NULL, ∞)}]\n" +
					"     │   ├─ colSet: (1,2)\n" +
					"     │   ├─ tableId: 1\n" +
					"     │   └─ Table\n" +
					"     │       ├─ name: t3\n" +
					"     │       └─ columns: [i j]\n" +
					"     └─ IndexedTableAccess(t4)\n" +
					"         ├─ index: [t4.x,t4.y]\n" +
					"         ├─ static: [{[NULL, ∞), [NULL, ∞)}]\n" +
					"         ├─ colSet: (3,4)\n" +
					"         ├─ tableId: 2\n" +
					"         └─ Table\n" +
					"             ├─ name: t4\n" +
					"             └─ columns: [x y]\n" +
					"",
			},
			{
				Query: `select /*+ MERGE_JOIN(t3, t4) */ * from t3 join t4 on t3.i = t4.x order by t3.j;`,
				Expected: []sql.Row{
					sql.Row{2, 2, 2, 2},
					sql.Row{3, 3, 3, 3},
				},
				ExpectedPlan: "Sort(t3.j:1!null ASC nullsFirst)\n" +
					" └─ MergeJoin\n" +
					"     ├─ cmp: Eq\n" +
					"     │   ├─ t3.i:0!null\n" +
					"     │   └─ t4.x:2!null\n" +
					"     ├─ IndexedTableAccess(t3)\n" +
					"     │   ├─ index: [t3.i,t3.j]\n" +
					"     │   ├─ static: [{[NULL, ∞), [NULL, ∞)}]\n" +
					"     │   ├─ colSet: (1,2)\n" +
					"     │   ├─ tableId: 1\n" +
					"     │   └─ Table\n" +
					"     │       ├─ name: t3\n" +
					"     │       └─ columns: [i j]\n" +
					"     └─ IndexedTableAccess(t4)\n" +
					"         ├─ index: [t4.x,t4.y]\n" +
					"         ├─ static: [{[NULL, ∞), [NULL, ∞)}]\n" +
					"         ├─ colSet: (3,4)\n" +
					"         ├─ tableId: 2\n" +
					"         └─ Table\n" +
					"             ├─ name: t4\n" +
					"             └─ columns: [x y]\n" +
					"",
			},
			{
				Query: `select /*+ MERGE_JOIN(t3, t4) */ * from t3 join t4 on t3.i = t4.x order by t4.y;`,
				Expected: []sql.Row{
					sql.Row{2, 2, 2, 2},
					sql.Row{3, 3, 3, 3},
				},
				ExpectedPlan: "Sort(t4.y:3!null ASC nullsFirst)\n" +
					" └─ MergeJoin\n" +
					"     ├─ cmp: Eq\n" +
					"     │   ├─ t3.i:0!null\n" +
					"     │   └─ t4.x:2!null\n" +
					"     ├─ IndexedTableAccess(t3)\n" +
					"     │   ├─ index: [t3.i,t3.j]\n" +
					"     │   ├─ static: [{[NULL, ∞), [NULL, ∞)}]\n" +
					"     │   ├─ colSet: (1,2)\n" +
					"     │   ├─ tableId: 1\n" +
					"     │   └─ Table\n" +
					"     │       ├─ name: t3\n" +
					"     │       └─ columns: [i j]\n" +
					"     └─ IndexedTableAccess(t4)\n" +
					"         ├─ index: [t4.x,t4.y]\n" +
					"         ├─ static: [{[NULL, ∞), [NULL, ∞)}]\n" +
					"         ├─ colSet: (3,4)\n" +
					"         ├─ tableId: 2\n" +
					"         └─ Table\n" +
					"             ├─ name: t4\n" +
					"             └─ columns: [x y]\n" +
					"",
			},
			{
				Query: `select /*+ MERGE_JOIN(t3, t4) */ * from t3 join t4 on t3.i = t4.x order by t3.i, t3.j desc;`,
				Expected: []sql.Row{
					sql.Row{2, 2, 2, 2},
					sql.Row{3, 3, 3, 3},
				},
				ExpectedPlan: "Sort(t3.i:0!null ASC nullsFirst, t3.j:1!null DESC nullsFirst)\n" +
					" └─ MergeJoin\n" +
					"     ├─ cmp: Eq\n" +
					"     │   ├─ t3.i:0!null\n" +
					"     │   └─ t4.x:2!null\n" +
					"     ├─ IndexedTableAccess(t3)\n" +
					"     │   ├─ index: [t3.i,t3.j]\n" +
					"     │   ├─ static: [{[NULL, ∞), [NULL, ∞)}]\n" +
					"     │   ├─ colSet: (1,2)\n" +
					"     │   ├─ tableId: 1\n" +
					"     │   └─ Table\n" +
					"     │       ├─ name: t3\n" +
					"     │       └─ columns: [i j]\n" +
					"     └─ IndexedTableAccess(t4)\n" +
					"         ├─ index: [t4.x,t4.y]\n" +
					"         ├─ static: [{[NULL, ∞), [NULL, ∞)}]\n" +
					"         ├─ colSet: (3,4)\n" +
					"         ├─ tableId: 2\n" +
					"         └─ Table\n" +
					"             ├─ name: t4\n" +
					"             └─ columns: [x y]\n" +
					"",
			},
			{
				Query: `select * from t1 join t2 order by t1.i;`,
				Expected: []sql.Row{
					sql.Row{1, 2},
					sql.Row{1, 3},
					sql.Row{1, 4},
					sql.Row{2, 2},
					sql.Row{2, 3},
					sql.Row{2, 4},
					sql.Row{3, 2},
					sql.Row{3, 3},
					sql.Row{3, 4},
				},
				ExpectedPlan: "CrossJoin\n" +
					" ├─ IndexedTableAccess(t1)\n" +
					" │   ├─ index: [t1.i]\n" +
					" │   ├─ static: [{[NULL, ∞)}]\n" +
					" │   ├─ colSet: (1)\n" +
					" │   ├─ tableId: 1\n" +
					" │   └─ Table\n" +
					" │       ├─ name: t1\n" +
					" │       └─ columns: [i]\n" +
					" └─ ProcessTable\n" +
					"     └─ Table\n" +
					"         ├─ name: t2\n" +
					"         └─ columns: [j]\n" +
					"",
			},
			{
				Query: `select * from t1 join t2 order by t2.j;`,
				Expected: []sql.Row{
					sql.Row{1, 2},
					sql.Row{2, 2},
					sql.Row{3, 2},
					sql.Row{1, 3},
					sql.Row{2, 3},
					sql.Row{3, 3},
					sql.Row{1, 4},
					sql.Row{2, 4},
					sql.Row{3, 4},
				},
				ExpectedPlan: "Project\n" +
					" ├─ columns: [t1.i:1!null, t2.j:0!null]\n" +
					" └─ CrossJoin\n" +
					"     ├─ IndexedTableAccess(t2)\n" +
					"     │   ├─ index: [t2.j]\n" +
					"     │   ├─ static: [{[NULL, ∞)}]\n" +
					"     │   ├─ colSet: (2)\n" +
					"     │   ├─ tableId: 2\n" +
					"     │   └─ Table\n" +
					"     │       ├─ name: t2\n" +
					"     │       └─ columns: [j]\n" +
					"     └─ ProcessTable\n" +
					"         └─ Table\n" +
					"             ├─ name: t1\n" +
					"             └─ columns: [i]\n" +
					"",
			},
			{
				Query: `select * from t1 join t2 order by t1.i desc;`,
				Expected: []sql.Row{
					sql.Row{3, 2},
					sql.Row{3, 3},
					sql.Row{3, 4},
					sql.Row{2, 2},
					sql.Row{2, 3},
					sql.Row{2, 4},
					sql.Row{1, 2},
					sql.Row{1, 3},
					sql.Row{1, 4},
				},
				ExpectedPlan: "CrossJoin\n" +
					" ├─ IndexedTableAccess(t1)\n" +
					" │   ├─ index: [t1.i]\n" +
					" │   ├─ static: [{[NULL, ∞)}]\n" +
					" │   ├─ reverse: true\n" +
					" │   ├─ colSet: (1)\n" +
					" │   ├─ tableId: 1\n" +
					" │   └─ Table\n" +
					" │       ├─ name: t1\n" +
					" │       └─ columns: [i]\n" +
					" └─ ProcessTable\n" +
					"     └─ Table\n" +
					"         ├─ name: t2\n" +
					"         └─ columns: [j]\n" +
					"",
			},
			{
				Query: `select * from t1 join t2 where t1.i > 1 and t1.i < 3 and t2.j > 2 and t2.j < 4 order by t1.i;`,
				Expected: []sql.Row{
					sql.Row{2, 3},
				},
				ExpectedPlan: "CrossJoin\n" +
					" ├─ IndexedTableAccess(t1)\n" +
					" │   ├─ index: [t1.i]\n" +
					" │   ├─ static: [{(1, 3)}]\n" +
					" │   ├─ colSet: (1)\n" +
					" │   ├─ tableId: 1\n" +
					" │   └─ Table\n" +
					" │       ├─ name: t1\n" +
					" │       └─ columns: [i]\n" +
					" └─ IndexedTableAccess(t2)\n" +
					"     ├─ index: [t2.j]\n" +
					"     ├─ static: [{(2, 4)}]\n" +
					"     ├─ colSet: (2)\n" +
					"     ├─ tableId: 2\n" +
					"     └─ Table\n" +
					"         ├─ name: t2\n" +
					"         └─ columns: [j]\n" +
					"",
			},
			{
				Query: `select * from t3 join t4 where t3.i = 1 and t4.x = 3 order by t3.i;`,
				Expected: []sql.Row{
					sql.Row{1, 1, 3, 3},
					sql.Row{1, 2, 3, 3},
				},
				ExpectedPlan: "CrossJoin\n" +
					" ├─ IndexedTableAccess(t3)\n" +
					" │   ├─ index: [t3.i,t3.j]\n" +
					" │   ├─ static: [{[1, 1], [NULL, ∞)}]\n" +
					" │   ├─ colSet: (1,2)\n" +
					" │   ├─ tableId: 1\n" +
					" │   └─ Table\n" +
					" │       ├─ name: t3\n" +
					" │       └─ columns: [i j]\n" +
					" └─ IndexedTableAccess(t4)\n" +
					"     ├─ index: [t4.x,t4.y]\n" +
					"     ├─ static: [{[3, 3], [NULL, ∞)}]\n" +
					"     ├─ colSet: (3,4)\n" +
					"     ├─ tableId: 2\n" +
					"     └─ Table\n" +
					"         ├─ name: t4\n" +
					"         └─ columns: [x y]\n" +
					"",
			},
			{
				Query: `select * from t3 join t4 where t3.j = 2 and t4.x = 3 order by t3.i desc;`,
				Expected: []sql.Row{
					sql.Row{2, 2, 3, 3},
					sql.Row{1, 2, 3, 3},
				},
				ExpectedPlan: "CrossJoin\n" +
					" ├─ Filter\n" +
					" │   ├─ Eq\n" +
					" │   │   ├─ t3.j:1!null\n" +
					" │   │   └─ 2 (int)\n" +
					" │   └─ IndexedTableAccess(t3)\n" +
					" │       ├─ index: [t3.i,t3.j]\n" +
					" │       ├─ static: [{[NULL, ∞), [NULL, ∞)}]\n" +
					" │       ├─ reverse: true\n" +
					" │       ├─ colSet: (1,2)\n" +
					" │       ├─ tableId: 1\n" +
					" │       └─ Table\n" +
					" │           ├─ name: t3\n" +
					" │           └─ columns: [i j]\n" +
					" └─ IndexedTableAccess(t4)\n" +
					"     ├─ index: [t4.x,t4.y]\n" +
					"     ├─ static: [{[3, 3], [NULL, ∞)}]\n" +
					"     ├─ colSet: (3,4)\n" +
					"     ├─ tableId: 2\n" +
					"     └─ Table\n" +
					"         ├─ name: t4\n" +
					"         └─ columns: [x y]\n" +
					"",
			},
			{
				Query: `select * from t1 inner join t2 where t1.i < t2.j order by t1.i;`,
				Expected: []sql.Row{
					sql.Row{1, 2},
					sql.Row{1, 3},
					sql.Row{1, 4},
					sql.Row{2, 3},
					sql.Row{2, 4},
					sql.Row{3, 4},
				},
				ExpectedPlan: "InnerJoin\n" +
					" ├─ LessThan\n" +
					" │   ├─ t1.i:0!null\n" +
					" │   └─ t2.j:1!null\n" +
					" ├─ IndexedTableAccess(t1)\n" +
					" │   ├─ index: [t1.i]\n" +
					" │   ├─ static: [{[NULL, ∞)}]\n" +
					" │   ├─ colSet: (1)\n" +
					" │   ├─ tableId: 1\n" +
					" │   └─ Table\n" +
					" │       ├─ name: t1\n" +
					" │       └─ columns: [i]\n" +
					" └─ ProcessTable\n" +
					"     └─ Table\n" +
					"         ├─ name: t2\n" +
					"         └─ columns: [j]\n" +
					"",
			},
			{
				Query: `select * from t1 inner join t2 where t1.i < t2.j order by t2.j desc;`,
				Expected: []sql.Row{
					sql.Row{1, 4},
					sql.Row{2, 4},
					sql.Row{3, 4},
					sql.Row{1, 3},
					sql.Row{2, 3},
					sql.Row{1, 2},
				},
				ExpectedPlan: "Project\n" +
					" ├─ columns: [t1.i:1!null, t2.j:0!null]\n" +
					" └─ InnerJoin\n" +
					"     ├─ LessThan\n" +
					"     │   ├─ t1.i:1!null\n" +
					"     │   └─ t2.j:0!null\n" +
					"     ├─ IndexedTableAccess(t2)\n" +
					"     │   ├─ index: [t2.j]\n" +
					"     │   ├─ static: [{[NULL, ∞)}]\n" +
					"     │   ├─ reverse: true\n" +
					"     │   ├─ colSet: (2)\n" +
					"     │   ├─ tableId: 2\n" +
					"     │   └─ Table\n" +
					"     │       ├─ name: t2\n" +
					"     │       └─ columns: [j]\n" +
					"     └─ ProcessTable\n" +
					"         └─ Table\n" +
					"             ├─ name: t1\n" +
					"             └─ columns: [i]\n" +
					"",
			},
			{
				Query: `select * from t3 inner join t4 where i != x order by t3.i, t3.j;`,
				Expected: []sql.Row{
					sql.Row{1, 1, 2, 2},
					sql.Row{1, 1, 3, 3},
					sql.Row{1, 1, 4, 4},
					sql.Row{1, 2, 2, 2},
					sql.Row{1, 2, 3, 3},
					sql.Row{1, 2, 4, 4},
					sql.Row{2, 2, 3, 3},
					sql.Row{2, 2, 4, 4},
					sql.Row{3, 3, 2, 2},
					sql.Row{3, 3, 4, 4},
				},
				ExpectedPlan: "InnerJoin\n" +
					" ├─ NOT\n" +
					" │   └─ Eq\n" +
					" │       ├─ t3.i:0!null\n" +
					" │       └─ t4.x:2!null\n" +
					" ├─ IndexedTableAccess(t3)\n" +
					" │   ├─ index: [t3.i,t3.j]\n" +
					" │   ├─ static: [{[NULL, ∞), [NULL, ∞)}]\n" +
					" │   ├─ colSet: (1,2)\n" +
					" │   ├─ tableId: 1\n" +
					" │   └─ Table\n" +
					" │       ├─ name: t3\n" +
					" │       └─ columns: [i j]\n" +
					" └─ ProcessTable\n" +
					"     └─ Table\n" +
					"         ├─ name: t4\n" +
					"         └─ columns: [x y]\n" +
					"",
			},
		},
	},
	{
		Name: "Recursive CTE inside NOT EXISTS clause with correlated column filter",
		SetUpScript: []string{
			`CREATE TABLE issues (id INT PRIMARY KEY, title TEXT, status TEXT);`,
			`CREATE TABLE dependencies (issue_id INT, depends_on_id INT, type TEXT);`,
			`INSERT INTO issues (id, title, status) VALUES
					(1, 'Login API',        'open'),
					(2, 'Auth Library',    'in_progress'),
					(3, 'User Profile',    'open'),
					(4, 'Profile UI',      'open'),
					(5, 'Settings Page',   'open'),
					(6, 'Marketing Page',  'open'),
					(7, 'Old Feature',     'closed');`,
			`INSERT INTO dependencies (issue_id, depends_on_id, type) VALUES
					(3, 1, 'blocks'),
					(3, 2, 'blocks'),
					(4, 3, 'parent-child'),
					(5, 4, 'parent-child');`,
		},
		Assertions: []ScriptTestAssertion{
			{
				Query: `WITH RECURSIVE
					  blocked_directly AS (
						SELECT DISTINCT d.issue_id
						FROM dependencies d
						JOIN issues blocker ON d.depends_on_id = blocker.id
						WHERE d.type = 'blocks'
						  AND blocker.status IN ('open', 'in_progress', 'blocked', 'deferred', 'hooked')
					  ),
					  blocked_transitively AS (
						SELECT issue_id, 0 as depth
						FROM blocked_directly
						UNION ALL
						SELECT d.issue_id, bt.depth + 1
						FROM blocked_transitively bt
						JOIN dependencies d ON d.depends_on_id = bt.issue_id
						WHERE d.type = 'parent-child'
						  AND bt.depth < 50
					  )
					SELECT i.*
					FROM issues i
					WHERE i.status = 'open'
					  AND NOT EXISTS (
						SELECT 1 FROM blocked_transitively WHERE issue_id = i.id
					  );`,
				Expected: []sql.Row{
					sql.Row{1, "Login API", "open"},
					sql.Row{6, "Marketing Page", "open"},
				},
				ExpectedPlan: "AntiJoinIncludingNulls\n" +
					" ├─ Eq\n" +
					" │   ├─ blocked_transitively.issue_id:3\n" +
					" │   └─ i.id:0!null\n" +
					" ├─ Filter\n" +
					" │   ├─ Eq\n" +
					" │   │   ├─ i.status:2\n" +
					" │   │   └─ open (longtext)\n" +
					" │   └─ TableAlias(i)\n" +
					" │       └─ ProcessTable\n" +
					" │           └─ Table\n" +
					" │               ├─ name: issues\n" +
					" │               └─ columns: [id title status]\n" +
					" └─ CachedResults\n" +
					"     └─ SubqueryAlias\n" +
					"         ├─ name: blocked_transitively\n" +
					"         ├─ outerVisibility: true\n" +
					"         ├─ isLateral: false\n" +
					"         ├─ cacheable: true\n" +
					"         ├─ colSet: (20,21)\n" +
					"         ├─ tableId: 7\n" +
					"         └─ RecursiveCTE\n" +
					"             └─ Union all\n" +
					"                 ├─ Project\n" +
					"                 │   ├─ columns: [blocked_directly.issue_id:0, 0 (tinyint)->depth:9]\n" +
					"                 │   └─ SubqueryAlias\n" +
					"                 │       ├─ name: blocked_directly\n" +
					"                 │       ├─ outerVisibility: false\n" +
					"                 │       ├─ isLateral: false\n" +
					"                 │       ├─ cacheable: true\n" +
					"                 │       ├─ colSet: (8)\n" +
					"                 │       ├─ tableId: 4\n" +
					"                 │       └─ Distinct\n" +
					"                 │           └─ Project\n" +
					"                 │               ├─ columns: [d.issue_id:0]\n" +
					"                 │               └─ LookupJoin\n" +
					"                 │                   ├─ Filter\n" +
					"                 │                   │   ├─ Eq\n" +
					"                 │                   │   │   ├─ d.type:2\n" +
					"                 │                   │   │   └─ blocks (longtext)\n" +
					"                 │                   │   └─ TableAlias(d)\n" +
					"                 │                   │       └─ Table\n" +
					"                 │                   │           ├─ name: dependencies\n" +
					"                 │                   │           ├─ columns: [issue_id depends_on_id type]\n" +
					"                 │                   │           ├─ colSet: (1-3)\n" +
					"                 │                   │           └─ tableId: 1\n" +
					"                 │                   └─ Filter\n" +
					"                 │                       ├─ HashIn\n" +
					"                 │                       │   ├─ blocker.status:1\n" +
					"                 │                       │   └─ TUPLE(open (longtext), in_progress (longtext), blocked (longtext), deferred (longtext), hooked (longtext))\n" +
					"                 │                       └─ TableAlias(blocker)\n" +
					"                 │                           └─ IndexedTableAccess(issues)\n" +
					"                 │                               ├─ index: [issues.id]\n" +
					"                 │                               ├─ keys: [d.depends_on_id:1]\n" +
					"                 │                               ├─ colSet: (4-6)\n" +
					"                 │                               ├─ tableId: 2\n" +
					"                 │                               └─ Table\n" +
					"                 │                                   ├─ name: issues\n" +
					"                 │                                   └─ columns: [id status]\n" +
					"                 └─ Project\n" +
					"                     ├─ columns: [d.issue_id:0, (bt.depth:4!null + 1 (tinyint))->bt.depth + 1:0]\n" +
					"                     └─ InnerJoin\n" +
					"                         ├─ AND\n" +
					"                         │   ├─ LessThan\n" +
					"                         │   │   ├─ bt.depth:7!null\n" +
					"                         │   │   └─ 50 (bigint)\n" +
					"                         │   └─ Eq\n" +
					"                         │       ├─ d.depends_on_id:4\n" +
					"                         │       └─ bt.issue_id:6\n" +
					"                         ├─ Filter\n" +
					"                         │   ├─ Eq\n" +
					"                         │   │   ├─ d.type:2\n" +
					"                         │   │   └─ parent-child (longtext)\n" +
					"                         │   └─ TableAlias(d)\n" +
					"                         │       └─ Table\n" +
					"                         │           ├─ name: dependencies\n" +
					"                         │           ├─ columns: [issue_id depends_on_id type]\n" +
					"                         │           ├─ colSet: (14-16)\n" +
					"                         │           └─ tableId: 8\n" +
					"                         └─ TableAlias(bt)\n" +
					"                             └─ RecursiveTable(blocked_transitively)\n" +
					"",
			},
		},
	},
}
