// Copyright 2020-2021 Dolthub, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package queries

import (
	"github.com/dolthub/go-mysql-server/sql"
	"github.com/dolthub/go-mysql-server/sql/plan"
	"github.com/dolthub/go-mysql-server/sql/types"
	"github.com/dolthub/vitess/go/vt/sqlparser"
	"gopkg.in/src-d/go-errors.v1"
)

type ScriptTest struct {
	// Name of the script test
	Name string
	// The sql statements to execute as setup, in order. Results are not checked, but statements must not error.
	SetUpScript []string
	// The set of assertions to make after setup, in order
	Assertions []ScriptTestAssertion
	// For tests that make a single assertion, Query can be set for the single assertion
	Query string
	// For tests that make a single assertion, Expected can be set for the single assertion
	Expected []sql.Row
	// For tests that make a single assertion, ExpectedErr can be set for the expected error
	ExpectedErr *errors.Kind
	// For tests that make a single assertion, ExpectedIndexes can be set for the string representation of indexes that we expect to appear in the query plan
	ExpectedIndexes []string
	// For tests that perform join operations, JoinTypes can be set for the type of merge we expect to perform.
	JoinTypes []plan.JoinType
	// SkipPrepared is true when we skip a test for prepared statements only
	SkipPrepared bool
	// Dialect is the supported dialect for this script, which must match the dialect of the harness if specified.
	// The script is skipped if the dialect doesn't match.
	Dialect string
	// Skip is used to completely skip a test, not execute any part of the script, and to record it as a skipped test in
	// the test suite results.
	Skip bool
}

type ScriptTestAssertion struct {
	Query       string
	Expected    []sql.Row
	ExpectedErr *errors.Kind
	// ExpectedErrStr should be set for tests that expect a specific error string this is not linked to a custom error.
	// In most cases, errors should be linked to a custom error, however there are exceptions where this is not possible,
	// such as the use of the SIGNAL statement.
	ExpectedErrStr string

	// SkipWarnings is used to skip the warnings count check
	SkipWarnings bool

	// ExpectedWarning contains the expected warning code when a query generates warnings but not errors.
	ExpectedWarning int

	// ExpectedWarningsCount is used to test the expected number of warnings generated by a query.
	// The ExpectedWarning field must be set for warning counts to be checked.
	ExpectedWarningsCount int

	// ExpectedWarningMessageSubstring is used to test the contents of warning messages generated by a
	// query. The ExpectedWarning field must be set for warning messages to be checked.
	ExpectedWarningMessageSubstring string

	// ExpectedColumns indicates the Name and Type of the columns expected; no other schema fields are tested.
	ExpectedColumns sql.Schema

	// The string representation of indexes that we expect to appear in the query plan
	ExpectedIndexes []string

	// For tests that perform join operations, JoinTypes can be set for the type of merge we expect to perform.
	JoinTypes []plan.JoinType

	// For tests that expect a specific plan
	ExpectedPlan string

	// NewSession instructs the test framework that this assertion requires a new session to be created before the
	// query is executed. This is generally only needed when a test script is testing functionality that invalidates
	// a session and prevents additional queries from being executed on the session.
	NewSession bool

	// SkipResultsCheck is used to skip assertions on expected Rows returned from a query. This should be used
	// sparingly, such as in cases where you only want to test warning messages.
	SkipResultsCheck bool

	// Skip is used to completely skip a test, not execute its query at all, and record it as a skipped test
	// in the test suite results.
	Skip bool

	// SkipResultCheckOnServerEngine is used when the result of over the wire test does not match the result from the engine test.
	// It should be fixed in the future.
	SkipResultCheckOnServerEngine bool

	// Bindings are variable mappings only used for prepared tests
	Bindings map[string]sqlparser.Expr

	// CheckIndexedAccess indicates whether we should verify the query plan uses an index
	CheckIndexedAccess bool

	// Dialect is the supported dialect for this assertion, which must match the dialect of the harness if specified.
	// The assertion is skipped if the dialect doesn't match.
	Dialect string
}

// ScriptTests are a set of test scripts to run.
// Unlike other engine tests, ScriptTests must be self-contained. No other tables are created outside the definition of
// the tests.
var ScriptTests = []ScriptTest{
	// Preserve the original order for prepared tests and other consumers of the combined suite.
	JoinsAndSubqueriesScriptTests[0],
	AggregationScriptTests[0],
	JoinsAndSubqueriesScriptTests[1],
	SessionScriptTests[0],
	IntegersScriptTests[0],
	IntegersScriptTests[1],
	IntegersScriptTests[2],
	SessionScriptTests[1],
	WritesScriptTests[0],
	StringsScriptTests[0],
	SessionScriptTests[2],
	AggregationScriptTests[1],
	AggregationScriptTests[2],
	ConversionsScriptTests[0],
	ConversionsScriptTests[1],
	IndexesScriptTests[0],
	ConversionsScriptTests[2],
	ConversionsScriptTests[3],
	TemporalScriptTests[0],
	StringsScriptTests[1],
	AggregationScriptTests[3],
	AggregationScriptTests[4],
	ExpressionsScriptTests[0],
	JoinsAndSubqueriesScriptTests[2],
	IndexesScriptTests[1],
	JoinsAndSubqueriesScriptTests[3],
	JoinsAndSubqueriesScriptTests[4],
	ExpressionsScriptTests[1],
	WritesScriptTests[1],
	WritesScriptTests[2],
	AggregationScriptTests[5],
	IndexesScriptTests[2],
	IndexesScriptTests[3],
	JoinsAndSubqueriesScriptTests[5],
	JoinsAndSubqueriesScriptTests[6],
	JoinsAndSubqueriesScriptTests[7],
	JoinsAndSubqueriesScriptTests[8],
	JoinsAndSubqueriesScriptTests[9],
	IndexesScriptTests[4],
	IndexesScriptTests[5],
	WritesScriptTests[3],
	AggregationScriptTests[6],
	AggregationScriptTests[7],
	SchemaScriptTests[0],
	SchemaScriptTests[1],
	AggregationScriptTests[8],
	WritesScriptTests[4],
	WritesScriptTests[5],
	JoinsAndSubqueriesScriptTests[10],
	ExpressionsScriptTests[2],
	IndexesScriptTests[6],
	JoinsAndSubqueriesScriptTests[11],
	JoinsAndSubqueriesScriptTests[12],
	JoinsAndSubqueriesScriptTests[13],
	JoinsAndSubqueriesScriptTests[14],
	JoinsAndSubqueriesScriptTests[15],
	JoinsAndSubqueriesScriptTests[16],
	JoinsAndSubqueriesScriptTests[17],
	JoinsAndSubqueriesScriptTests[18],
	JoinsAndSubqueriesScriptTests[19],
	JoinsAndSubqueriesScriptTests[20],
	SessionScriptTests[3],
	SessionScriptTests[4],
	SessionScriptTests[5],
	SessionScriptTests[6],
	WritesScriptTests[6],
	WritesScriptTests[7],
	WritesScriptTests[8],
	WritesScriptTests[9],
	SessionScriptTests[7],
	ExpressionsScriptTests[3],
	SessionScriptTests[8],
	WritesScriptTests[10],
	JoinsAndSubqueriesScriptTests[21],
	AggregationScriptTests[9],
	JoinsAndSubqueriesScriptTests[22],
	JoinsAndSubqueriesScriptTests[23],
	JoinsAndSubqueriesScriptTests[24],
	JoinsAndSubqueriesScriptTests[25],
	JoinsAndSubqueriesScriptTests[26],
	ConversionsScriptTests[4],
	SchemaScriptTests[2],
	AggregationScriptTests[10],
	JoinsAndSubqueriesScriptTests[27],
	SchemaScriptTests[3],
	TemporalScriptTests[1],
	TemporalScriptTests[2],
	TemporalScriptTests[3],
	ExpressionsScriptTests[4],
	JoinsAndSubqueriesScriptTests[28],
	JoinsAndSubqueriesScriptTests[29],
	IndexesScriptTests[7],
	IndexesScriptTests[8],
	ConversionsScriptTests[5],
	ConversionsScriptTests[6],
	JoinsAndSubqueriesScriptTests[30],
	SchemaScriptTests[4],
	IndexesScriptTests[9],
	WritesScriptTests[11],
	IndexesScriptTests[10],
	IndexesScriptTests[11],
	ConversionsScriptTests[7],
	IndexesScriptTests[12],
	IndexesScriptTests[13],
	SchemaScriptTests[5],
	SchemaScriptTests[6],
	SchemaScriptTests[7],
	JoinsAndSubqueriesScriptTests[31],
	ConversionsScriptTests[8],
	SchemaScriptTests[8],
	StringsScriptTests[2],
	ConversionsScriptTests[9],
	ConversionsScriptTests[10],
	ConversionsScriptTests[11],
	SchemaScriptTests[9],
	JoinsAndSubqueriesScriptTests[32],
	AggregationScriptTests[11],
	JoinsAndSubqueriesScriptTests[33],
	SchemaScriptTests[10],
	SchemaScriptTests[11],
	ConversionsScriptTests[12],
	ConversionsScriptTests[13],
	IntegersScriptTests[3],
	IntegersScriptTests[4],
	ConversionsScriptTests[14],
	TemporalScriptTests[4],
	WritesScriptTests[12],
	ConversionsScriptTests[15],
	WritesScriptTests[13],
	JoinsAndSubqueriesScriptTests[34],
	ConversionsScriptTests[16],
	ConversionsScriptTests[17],
	JoinsAndSubqueriesScriptTests[35],
	ExpressionsScriptTests[5],
	IndexesScriptTests[14],
	SchemaScriptTests[12],
	SchemaScriptTests[13],
	TemporalScriptTests[5],
	TemporalScriptTests[6],
	TemporalScriptTests[7],
	TemporalScriptTests[8],
	IndexesScriptTests[15],
	WritesScriptTests[14],
	IndexesScriptTests[16],
	ExpressionsScriptTests[6],
	TemporalScriptTests[9],
	TemporalScriptTests[10],
	SchemaScriptTests[14],
	SessionScriptTests[9],
	IndexesScriptTests[17],
	IndexesScriptTests[18],
	IndexesScriptTests[19],
	IndexesScriptTests[20],
	IndexesScriptTests[21],
	WritesScriptTests[15],
	IndexesScriptTests[22],
	IndexesScriptTests[23],
	ConversionsScriptTests[18],
	ConversionsScriptTests[19],
	ExpressionsScriptTests[7],
	ExpressionsScriptTests[8],
	ConversionsScriptTests[20],
	JoinsAndSubqueriesScriptTests[36],
	IndexesScriptTests[24],
	ConversionsScriptTests[21],
	JoinsAndSubqueriesScriptTests[37],
	ConversionsScriptTests[22],
	ConversionsScriptTests[23],
	TemporalScriptTests[11],
	ConversionsScriptTests[24],
	ConversionsScriptTests[25],
	AggregationScriptTests[12],
	ConversionsScriptTests[26],
	IndexesScriptTests[25],
	JoinsAndSubqueriesScriptTests[38],
	TemporalScriptTests[12],
	IndexesScriptTests[26],
	IndexesScriptTests[27],
	IndexesScriptTests[28],
	IndexesScriptTests[29],
	ExpressionsScriptTests[9],
	SchemaScriptTests[15],
	SchemaScriptTests[16],
	IndexesScriptTests[30],
	SchemaScriptTests[17],
	StringsScriptTests[3],
	StringsScriptTests[4],
	StringsScriptTests[5],
	StringsScriptTests[6],
	StringsScriptTests[7],
	TemporalScriptTests[13],
	ExpressionsScriptTests[10],
	StringsScriptTests[8],
	IndexesScriptTests[31],
	SessionScriptTests[10],
	SessionScriptTests[11],
	SessionScriptTests[12],
	SessionScriptTests[13],
	ExpressionsScriptTests[11],
	ExpressionsScriptTests[12],
	IntegersScriptTests[5],
	IntegersScriptTests[6],
	AggregationScriptTests[13],
	WritesScriptTests[16],
	ExpressionsScriptTests[13],
	TemporalScriptTests[14],
	StringsScriptTests[9],
	ExpressionsScriptTests[14],
	StringsScriptTests[10],
	WritesScriptTests[17],
	WritesScriptTests[18],
	WritesScriptTests[19],
	WritesScriptTests[20],
	WritesScriptTests[21],
	WritesScriptTests[22],
	EnumsAndSetsScriptTests[0],
	EnumsAndSetsScriptTests[1],
	EnumsAndSetsScriptTests[2],
	EnumsAndSetsScriptTests[3],
	EnumsAndSetsScriptTests[4],
	EnumsAndSetsScriptTests[5],
	EnumsAndSetsScriptTests[6],
	EnumsAndSetsScriptTests[7],
	EnumsAndSetsScriptTests[8],
	EnumsAndSetsScriptTests[9],
	EnumsAndSetsScriptTests[10],
	EnumsAndSetsScriptTests[11],
	EnumsAndSetsScriptTests[12],
	WritesScriptTests[23],
	EnumsAndSetsScriptTests[13],
	EnumsAndSetsScriptTests[14],
	EnumsAndSetsScriptTests[15],
	EnumsAndSetsScriptTests[16],
	EnumsAndSetsScriptTests[17],
	EnumsAndSetsScriptTests[18],
	EnumsAndSetsScriptTests[19],
	EnumsAndSetsScriptTests[20],
	EnumsAndSetsScriptTests[21],
	EnumsAndSetsScriptTests[22],
	JoinsAndSubqueriesScriptTests[39],
	EnumsAndSetsScriptTests[23],
	EnumsAndSetsScriptTests[24],
	EnumsAndSetsScriptTests[25],
	EnumsAndSetsScriptTests[26],
	EnumsAndSetsScriptTests[27],
	EnumsAndSetsScriptTests[28],
	EnumsAndSetsScriptTests[29],
	EnumsAndSetsScriptTests[30],
	EnumsAndSetsScriptTests[31],
	EnumsAndSetsScriptTests[32],
	EnumsAndSetsScriptTests[33],
	EnumsAndSetsScriptTests[34],
	IntegersScriptTests[7],
	IntegersScriptTests[8],
	IntegersScriptTests[9],
	IntegersScriptTests[10],
	IntegersScriptTests[11],
	IntegersScriptTests[12],
	ConversionsScriptTests[27],
	WritesScriptTests[24],
	ConversionsScriptTests[28],
	ConversionsScriptTests[29],
	ConversionsScriptTests[30],
	TemporalScriptTests[15],
	TemporalScriptTests[16],
	TemporalScriptTests[17],
	TemporalScriptTests[18],
	TemporalScriptTests[19],
	TemporalScriptTests[20],
	TemporalScriptTests[21],
	TemporalScriptTests[22],
	TemporalScriptTests[23],
	TemporalScriptTests[24],
	TemporalScriptTests[25],
	TemporalScriptTests[26],
	IndexesScriptTests[32],
	AggregationScriptTests[14],
	JoinsAndSubqueriesScriptTests[40],
	AggregationScriptTests[15],
	AggregationScriptTests[16],
	JoinsAndSubqueriesScriptTests[41],
	StringsScriptTests[11],
	JoinsAndSubqueriesScriptTests[42],
	AggregationScriptTests[17],
	JoinsAndSubqueriesScriptTests[43],
	JoinsAndSubqueriesScriptTests[44],
	JoinsAndSubqueriesScriptTests[45],
	JoinsAndSubqueriesScriptTests[46],
	JoinsAndSubqueriesScriptTests[47],
	JoinsAndSubqueriesScriptTests[48],
	ExpressionsScriptTests[15],
	JoinsAndSubqueriesScriptTests[49],
	IndexesScriptTests[33],
	ExpressionsScriptTests[16],
	JoinsAndSubqueriesScriptTests[50],
	JoinsAndSubqueriesScriptTests[51],
	ConversionsScriptTests[31],
	ConversionsScriptTests[32],
	ConversionsScriptTests[33],
	ConversionsScriptTests[34],
	ConversionsScriptTests[35],
	ConversionsScriptTests[36],
	JoinsAndSubqueriesScriptTests[52],
	JoinsAndSubqueriesScriptTests[53],
	JoinsAndSubqueriesScriptTests[54],
	JoinsAndSubqueriesScriptTests[55],
	StringsScriptTests[12],
	StringsScriptTests[13],
	JoinsAndSubqueriesScriptTests[56],
	AggregationScriptTests[18],
	StringsScriptTests[14],
	WritesScriptTests[25],
	WritesScriptTests[26],
	IndexesScriptTests[34],
	IndexesScriptTests[35],
	IndexesScriptTests[36],
	IndexesScriptTests[37],
	IndexesScriptTests[38],
	IndexesScriptTests[39],
	IndexesScriptTests[40],
	StringsScriptTests[15],
}

var CreateDatabaseScripts = []ScriptTest{
	{
		// https://github.com/dolthub/dolt/pull/9830
		Name: "CREATE SCHEMA without database selection falls back to CREATE DATABASE",
		SetUpScript: []string{
			"CREATE DATABASE tmp",
			"USE tmp",
		},
		Dialect: "mysql",
		Assertions: []ScriptTestAssertion{
			{
				Query: "DROP DATABASE tmp",
			},
			{
				Query:    "CREATE SCHEMA NewDatabase",
				Expected: []sql.Row{{types.OkResult{RowsAffected: 1}}},
			},
			{
				Query:    "SHOW DATABASES",
				Expected: []sql.Row{{"NewDatabase"}, {"information_schema"}, {"mydb"}, {"mysql"}},
			},
			{
				Query:    "USE NewDatabase",
				Expected: []sql.Row{},
			},
			{
				Query:    "SELECT DATABASE()",
				Expected: []sql.Row{{"NewDatabase"}},
			},
			{
				Query:    "CREATE TABLE test_table (id INT PRIMARY KEY)",
				Expected: []sql.Row{{types.OkResult{RowsAffected: 0}}},
			},
			{
				Query:    "SHOW TABLES",
				Expected: []sql.Row{{"test_table"}},
			},
			{
				Query:    "USE mydb",
				Expected: []sql.Row{},
			},
			{
				Query:    "DROP DATABASE NewDatabase",
				Expected: []sql.Row{{types.OkResult{RowsAffected: 1}}},
			},
		},
	},
	{
		Name: "CREATE DATABASE and create table",
		Assertions: []ScriptTestAssertion{
			{
				Query:    "CREATE DATABASE testdb",
				Expected: []sql.Row{{types.OkResult{RowsAffected: 1}}},
			},
			{
				Query:    "USE testdb",
				Expected: []sql.Row{},
			},
			{
				Query:    "SELECT DATABASE()",
				Expected: []sql.Row{{"testdb"}},
			},
			{
				Query:    "CREATE TABLE test (pk int primary key)",
				Expected: []sql.Row{{types.NewOkResult(0)}},
			},
			{
				Query:    "SHOW TABLES",
				Expected: []sql.Row{{"test"}},
			},
		},
	},
	{
		Name: "CREATE DATABASE IF NOT EXISTS",
		Assertions: []ScriptTestAssertion{
			{
				Query:    "CREATE DATABASE IF NOT EXISTS testdb2",
				Expected: []sql.Row{{types.OkResult{RowsAffected: 1}}},
			},
			{
				Query:    "USE testdb2",
				Expected: []sql.Row{},
			},
			{
				Query:    "SELECT DATABASE()",
				Expected: []sql.Row{{"testdb2"}},
			},
			{
				Query:    "CREATE TABLE test (pk int primary key)",
				Expected: []sql.Row{{types.NewOkResult(0)}},
			},
			{
				Query:    "SHOW TABLES",
				Expected: []sql.Row{{"test"}},
			},
		},
	},
	{
		Name: "CREATE SCHEMA",
		Assertions: []ScriptTestAssertion{
			{
				Query:    "CREATE SCHEMA testdb3",
				Expected: []sql.Row{{types.OkResult{RowsAffected: 1}}},
			},
			{
				Query:    "USE testdb3",
				Expected: []sql.Row{},
			},
			{
				Query:    "SELECT DATABASE()",
				Expected: []sql.Row{{"testdb3"}},
			},
			{
				Query:    "CREATE TABLE test (pk int primary key)",
				Expected: []sql.Row{{types.NewOkResult(0)}},
			},
			{
				Query:    "SHOW TABLES",
				Expected: []sql.Row{{"test"}},
			},
		},
	},
	{
		Name: "CREATE DATABASE error handling",
		Assertions: []ScriptTestAssertion{
			{
				Query:    "CREATE DATABASE newtestdb CHARACTER SET utf8mb4 ENCRYPTION='N'",
				Expected: []sql.Row{{types.NewOkResult(1)}},
			},
			{
				Query:    "SHOW WARNINGS /* 1 */",
				Expected: []sql.Row{{"Warning", 1235, "Setting CHARACTER SET, COLLATION and ENCRYPTION are not supported yet"}},
			},
			{
				Query:    "CREATE DATABASE newtest1db DEFAULT COLLATE binary ENCRYPTION='Y'",
				Expected: []sql.Row{{types.NewOkResult(1)}},
			},
			{
				Query: "SHOW WARNINGS /* 2 */",
				Expected: []sql.Row{
					{"Warning", 1235, "Setting CHARACTER SET, COLLATION and ENCRYPTION are not supported yet"},
				},
			},
			{
				Query:       "CREATE DATABASE mydb",
				ExpectedErr: sql.ErrDatabaseExists,
			},
			{
				Query:    "CREATE DATABASE IF NOT EXISTS mydb",
				Expected: []sql.Row{{types.OkResult{RowsAffected: 1}}},
			},
			{
				Query:    "SHOW WARNINGS /* 3 */",
				Expected: []sql.Row{{"Note", 1007, "Can't create database mydb; database exists "}},
			},
		},
	},
}

var DropDatabaseScripts = []ScriptTest{
	{
		Name: "DROP DATABASE correctly works",
		Assertions: []ScriptTestAssertion{
			{
				Query:    "DROP DATABASE mydb",
				Expected: []sql.Row{{types.OkResult{RowsAffected: 1}}},
			},
			{
				Query:    "SELECT DATABASE()",
				Expected: []sql.Row{{nil}},
			},
			{
				// TODO: incorrect error returned because the currentdb is not set to empty
				Skip:        true,
				Query:       "SHOW TABLES",
				ExpectedErr: sql.ErrNoDatabaseSelected,
			},
		},
	},
	{
		Name: "DROP DATABASE works on newly created databases.",
		SetUpScript: []string{
			"CREATE DATABASE testdb",
		},
		Assertions: []ScriptTestAssertion{
			{
				Query:    "USE testdb",
				Expected: []sql.Row{},
			},
			{
				Query:    "DROP DATABASE testdb",
				Expected: []sql.Row{{types.OkResult{RowsAffected: 1}}},
			},
			{
				Query:       "USE testdb",
				ExpectedErr: sql.ErrDatabaseNotFound,
			},
		},
	},
	{
		Name: "DROP DATABASE works on current database and sets current database to empty.",
		SetUpScript: []string{
			"CREATE DATABASE testdb",
			"USE TESTdb",
		},
		Assertions: []ScriptTestAssertion{
			{
				Query:    "DROP DATABASE TESTDB",
				Expected: []sql.Row{{types.OkResult{RowsAffected: 1}}},
			},
			{
				Query:    "SELECT DATABASE()",
				Expected: []sql.Row{{nil}},
			},
			{
				Query:       "USE testdb",
				ExpectedErr: sql.ErrDatabaseNotFound,
			},
		},
	},
	{
		Name: "DROP SCHEMA works on newly created databases.",
		SetUpScript: []string{
			"CREATE SCHEMA testdb",
		},
		Assertions: []ScriptTestAssertion{
			{
				Query:    "DROP SCHEMA TESTDB",
				Expected: []sql.Row{{types.OkResult{RowsAffected: 1}}},
			},
			{
				Query:       "USE testdb",
				ExpectedErr: sql.ErrDatabaseNotFound,
			},
		},
	},
	{
		Name: "DROP DATABASE IF EXISTS correctly works.",
		SetUpScript: []string{
			"DROP DATABASE mydb",
			"CREATE DATABASE testdb",
		},
		Assertions: []ScriptTestAssertion{
			{
				Query:    "DROP DATABASE IF EXISTS mydb",
				Expected: []sql.Row{{types.OkResult{RowsAffected: 0}}},
			},
			{
				Query:    "SHOW WARNINGS",
				Expected: []sql.Row{{"Note", 1008, "Can't drop database mydb; database doesn't exist "}},
			},
			{
				Query:    "DROP DATABASE IF EXISTS testdb",
				Expected: []sql.Row{{types.OkResult{RowsAffected: 1}}},
			},
			{
				Query:    "SHOW WARNINGS",
				Expected: []sql.Row{},
			},
			{
				Query:    "SELECT DATABASE()",
				Expected: []sql.Row{{nil}},
			},
			{
				Query:       "USE testdb",
				ExpectedErr: sql.ErrDatabaseNotFound,
			},
			{
				Query:    "DROP DATABASE IF EXISTS testdb",
				Expected: []sql.Row{{types.OkResult{RowsAffected: 0}}},
			},
			{
				Query:    "SHOW WARNINGS",
				Expected: []sql.Row{{"Note", 1008, "Can't drop database testdb; database doesn't exist "}},
			},
		},
	},
}
