// Code generated by plangen.

// Copyright 2025 Dolthub, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package queries

var TpccPlanTests = []QueryPlanTest{
	{
		Query: `
-- cycle 1a
SELECT c_discount, c_last, c_credit, w_tax FROM customer2, warehouse2 WHERE w_id = 1 AND c_w_id = w_id AND c_d_id = 9 AND c_id = 2151`,
		ExpectedPlan: "Project\n" +
			" ├─ columns: [customer2.c_discount:7, customer2.c_last:5, customer2.c_credit:6, warehouse2.w_tax:1]\n" +
			" └─ LookupJoin\n" +
			"     ├─ IndexedTableAccess(warehouse2)\n" +
			"     │   ├─ index: [warehouse2.w_id]\n" +
			"     │   ├─ static: [{[1, 1]}]\n" +
			"     │   ├─ colSet: (22-30)\n" +
			"     │   ├─ tableId: 2\n" +
			"     │   └─ Table\n" +
			"     │       ├─ name: warehouse2\n" +
			"     │       └─ columns: [w_id w_tax]\n" +
			"     └─ Filter\n" +
			"         ├─ AND\n" +
			"         │   ├─ Eq\n" +
			"         │   │   ├─ customer2.c_d_id:1!null\n" +
			"         │   │   └─ 9 (tinyint)\n" +
			"         │   └─ Eq\n" +
			"         │       ├─ customer2.c_id:0!null\n" +
			"         │       └─ 2151 (int)\n" +
			"         └─ IndexedTableAccess(customer2)\n" +
			"             ├─ index: [customer2.c_w_id,customer2.c_d_id,customer2.c_id]\n" +
			"             ├─ keys: [warehouse2.w_id:0!null 9 (tinyint) 2151 (int)]\n" +
			"             ├─ colSet: (1-21)\n" +
			"             ├─ tableId: 1\n" +
			"             └─ Table\n" +
			"                 ├─ name: customer2\n" +
			"                 └─ columns: [c_id c_d_id c_w_id c_last c_credit c_discount]\n" +
			"",
		ExpectedEstimates: "Project\n" +
			" ├─ columns: [customer2.c_discount, customer2.c_last, customer2.c_credit, warehouse2.w_tax]\n" +
			" └─ LookupJoin (estimated cost=3.300 rows=1)\n" +
			"     ├─ IndexedTableAccess(warehouse2)\n" +
			"     │   ├─ index: [warehouse2.w_id]\n" +
			"     │   ├─ filters: [{[1, 1]}]\n" +
			"     │   └─ columns: [w_id w_tax]\n" +
			"     └─ Filter\n" +
			"         ├─ ((customer2.c_d_id = 9) AND (customer2.c_id = 2151))\n" +
			"         └─ IndexedTableAccess(customer2)\n" +
			"             ├─ index: [customer2.c_w_id,customer2.c_d_id,customer2.c_id]\n" +
			"             ├─ columns: [c_id c_d_id c_w_id c_last c_credit c_discount]\n" +
			"             └─ keys: warehouse2.w_id, 9, 2151\n" +
			"",
		ExpectedAnalysis: "Project\n" +
			" ├─ columns: [customer2.c_discount, customer2.c_last, customer2.c_credit, warehouse2.w_tax]\n" +
			" └─ LookupJoin (estimated cost=3.300 rows=1) (actual rows=0 loops=1)\n" +
			"     ├─ IndexedTableAccess(warehouse2)\n" +
			"     │   ├─ index: [warehouse2.w_id]\n" +
			"     │   ├─ filters: [{[1, 1]}]\n" +
			"     │   └─ columns: [w_id w_tax]\n" +
			"     └─ Filter\n" +
			"         ├─ ((customer2.c_d_id = 9) AND (customer2.c_id = 2151))\n" +
			"         └─ IndexedTableAccess(customer2)\n" +
			"             ├─ index: [customer2.c_w_id,customer2.c_d_id,customer2.c_id]\n" +
			"             ├─ columns: [c_id c_d_id c_w_id c_last c_credit c_discount]\n" +
			"             └─ keys: warehouse2.w_id, 9, 2151\n" +
			"",
	},
	{
		Query: `SELECT d_next_o_id, d_tax FROM district2 WHERE d_w_id = 1 AND d_id = 9 FOR UPDATE`,
		ExpectedPlan: "Project\n" +
			" ├─ columns: [district2.d_next_o_id:3, district2.d_tax:2]\n" +
			" └─ IndexedTableAccess(district2)\n" +
			"     ├─ index: [district2.d_w_id,district2.d_id]\n" +
			"     ├─ static: [{[1, 1], [9, 9]}]\n" +
			"     ├─ colSet: (1-11)\n" +
			"     ├─ tableId: 1\n" +
			"     └─ Table\n" +
			"         ├─ name: district2\n" +
			"         └─ columns: [d_id d_w_id d_tax d_next_o_id]\n" +
			"",
		ExpectedEstimates: "Project\n" +
			" ├─ columns: [district2.d_next_o_id, district2.d_tax]\n" +
			" └─ IndexedTableAccess(district2)\n" +
			"     ├─ index: [district2.d_w_id,district2.d_id]\n" +
			"     ├─ filters: [{[1, 1], [9, 9]}]\n" +
			"     └─ columns: [d_id d_w_id d_tax d_next_o_id]\n" +
			"",
		ExpectedAnalysis: "Project\n" +
			" ├─ columns: [district2.d_next_o_id, district2.d_tax]\n" +
			" └─ IndexedTableAccess(district2)\n" +
			"     ├─ index: [district2.d_w_id,district2.d_id]\n" +
			"     ├─ filters: [{[1, 1], [9, 9]}]\n" +
			"     └─ columns: [d_id d_w_id d_tax d_next_o_id]\n" +
			"",
	},
	{
		Query: `UPDATE district2 SET d_next_o_id = 3002 WHERE d_id = 9 AND d_w_id= 1`,
		ExpectedPlan: "Update\n" +
			" └─ UpdateSource(SET district2.d_next_o_id:10 = 3002 (smallint))\n" +
			"     └─ IndexedTableAccess(district2)\n" +
			"         ├─ index: [district2.d_w_id,district2.d_id]\n" +
			"         ├─ static: [{[1, 1], [9, 9]}]\n" +
			"         ├─ colSet: (1-11)\n" +
			"         ├─ tableId: 1\n" +
			"         └─ Table\n" +
			"             ├─ name: district2\n" +
			"             └─ columns: [d_id d_w_id d_name d_street_1 d_street_2 d_city d_state d_zip d_tax d_ytd d_next_o_id]\n" +
			"",
	},
	{
		Query: `INSERT INTO orders2 (o_id, o_d_id, o_w_id, o_c_id, o_entry_d, o_ol_cnt, o_all_local) VALUES (3001,9,1,2151,NOW(),12,1)`,
		ExpectedPlan: "Insert(o_id, o_d_id, o_w_id, o_c_id, o_entry_d, o_ol_cnt, o_all_local)\n" +
			" ├─ InsertDestination\n" +
			" │   └─ ProcessTable\n" +
			" │       └─ Table\n" +
			" │           ├─ name: orders2\n" +
			" │           └─ columns: [o_id o_d_id o_w_id o_c_id o_entry_d o_carrier_id o_ol_cnt o_all_local]\n" +
			" └─ Project\n" +
			"     ├─ columns: [o_id:0!null, o_d_id:1!null, o_w_id:2!null, o_c_id:3, o_entry_d:4, , o_ol_cnt:5, o_all_local:6]\n" +
			"     └─ Values([3001 (smallint),9 (tinyint),1 (tinyint),2151 (smallint),NOW(),12 (tinyint),1 (tinyint)])\n" +
			"",
	},
	{
		Query: `INSERT INTO new_orders2 (no_o_id, no_d_id, no_w_id) VALUES (3001,9,1)`,
		ExpectedPlan: "Insert(no_o_id, no_d_id, no_w_id)\n" +
			" ├─ InsertDestination\n" +
			" │   └─ ProcessTable\n" +
			" │       └─ Table\n" +
			" │           ├─ name: new_orders2\n" +
			" │           └─ columns: [no_o_id no_d_id no_w_id]\n" +
			" └─ Project\n" +
			"     ├─ columns: [no_o_id:0!null, no_d_id:1!null, no_w_id:2!null]\n" +
			"     └─ Values([3001 (smallint),9 (tinyint),1 (tinyint)])\n" +
			"",
	},
	{
		Query: `SELECT i_price, i_name, i_data FROM item2 WHERE i_id = 2532`,
		ExpectedPlan: "Project\n" +
			" ├─ columns: [item2.i_price:2, item2.i_name:1, item2.i_data:3]\n" +
			" └─ IndexedTableAccess(item2)\n" +
			"     ├─ index: [item2.i_id]\n" +
			"     ├─ static: [{[2532, 2532]}]\n" +
			"     ├─ colSet: (1-5)\n" +
			"     ├─ tableId: 1\n" +
			"     └─ Table\n" +
			"         ├─ name: item2\n" +
			"         └─ columns: [i_id i_name i_price i_data]\n" +
			"",
		ExpectedEstimates: "Project\n" +
			" ├─ columns: [item2.i_price, item2.i_name, item2.i_data]\n" +
			" └─ IndexedTableAccess(item2)\n" +
			"     ├─ index: [item2.i_id]\n" +
			"     ├─ filters: [{[2532, 2532]}]\n" +
			"     └─ columns: [i_id i_name i_price i_data]\n" +
			"",
		ExpectedAnalysis: "Project\n" +
			" ├─ columns: [item2.i_price, item2.i_name, item2.i_data]\n" +
			" └─ IndexedTableAccess(item2)\n" +
			"     ├─ index: [item2.i_id]\n" +
			"     ├─ filters: [{[2532, 2532]}]\n" +
			"     └─ columns: [i_id i_name i_price i_data]\n" +
			"",
	},
	{
		Query: `SELECT s_quantity, s_data, s_dist_09 s_dist FROM stock2 WHERE s_i_id = 2532 AND s_w_id= 1 FOR UPDATE`,
		ExpectedPlan: "Project\n" +
			" ├─ columns: [stock2.s_quantity:2, stock2.s_data:4, stock2.s_dist_09:3->s_dist:0]\n" +
			" └─ IndexedTableAccess(stock2)\n" +
			"     ├─ index: [stock2.s_w_id,stock2.s_i_id]\n" +
			"     ├─ static: [{[1, 1], [2532, 2532]}]\n" +
			"     ├─ colSet: (1-17)\n" +
			"     ├─ tableId: 1\n" +
			"     └─ Table\n" +
			"         ├─ name: stock2\n" +
			"         └─ columns: [s_i_id s_w_id s_quantity s_dist_09 s_data]\n" +
			"",
		ExpectedEstimates: "Project\n" +
			" ├─ columns: [stock2.s_quantity, stock2.s_data, stock2.s_dist_09 as s_dist]\n" +
			" └─ IndexedTableAccess(stock2)\n" +
			"     ├─ index: [stock2.s_w_id,stock2.s_i_id]\n" +
			"     ├─ filters: [{[1, 1], [2532, 2532]}]\n" +
			"     └─ columns: [s_i_id s_w_id s_quantity s_dist_09 s_data]\n" +
			"",
		ExpectedAnalysis: "Project\n" +
			" ├─ columns: [stock2.s_quantity, stock2.s_data, stock2.s_dist_09 as s_dist]\n" +
			" └─ IndexedTableAccess(stock2)\n" +
			"     ├─ index: [stock2.s_w_id,stock2.s_i_id]\n" +
			"     ├─ filters: [{[1, 1], [2532, 2532]}]\n" +
			"     └─ columns: [s_i_id s_w_id s_quantity s_dist_09 s_data]\n" +
			"",
	},
	{
		Query: `UPDATE stock2 SET s_quantity = 39 WHERE s_i_id = 2532 AND s_w_id= 1`,
		ExpectedPlan: "Update\n" +
			" └─ UpdateSource(SET stock2.s_quantity:2 = 39 (tinyint))\n" +
			"     └─ IndexedTableAccess(stock2)\n" +
			"         ├─ index: [stock2.s_w_id,stock2.s_i_id]\n" +
			"         ├─ static: [{[1, 1], [2532, 2532]}]\n" +
			"         ├─ colSet: (1-17)\n" +
			"         ├─ tableId: 1\n" +
			"         └─ Table\n" +
			"             ├─ name: stock2\n" +
			"             └─ columns: [s_i_id s_w_id s_quantity s_dist_01 s_dist_02 s_dist_03 s_dist_04 s_dist_05 s_dist_06 s_dist_07 s_dist_08 s_dist_09 s_dist_10 s_ytd s_order_cnt s_remote_cnt s_data]\n" +
			"",
	},
	{
		Query: `INSERT INTO order_line2 (ol_o_id, ol_d_id, ol_w_id, ol_number, ol_i_id, ol_supply_w_id, ol_quantity, ol_amount, ol_dist_info) VALUES (
3001,9,1,1,2532,1,5,301,'kkkkkkkkkkkkkkkkkkkkkkkk')`,
		ExpectedPlan: "Insert(ol_o_id, ol_d_id, ol_w_id, ol_number, ol_i_id, ol_supply_w_id, ol_quantity, ol_amount, ol_dist_info)\n" +
			" ├─ InsertDestination\n" +
			" │   └─ ProcessTable\n" +
			" │       └─ Table\n" +
			" │           ├─ name: order_line2\n" +
			" │           └─ columns: [ol_o_id ol_d_id ol_w_id ol_number ol_i_id ol_supply_w_id ol_delivery_d ol_quantity ol_amount ol_dist_info]\n" +
			" └─ Project\n" +
			"     ├─ columns: [ol_o_id:0!null, ol_d_id:1!null, ol_w_id:2!null, ol_number:3!null, ol_i_id:4, ol_supply_w_id:5, , ol_quantity:6, ol_amount:7, ol_dist_info:8]\n" +
			"     └─ Values([3001 (smallint),9 (tinyint),1 (tinyint),1 (tinyint),2532 (smallint),1 (tinyint),5 (tinyint),301 (smallint),kkkkkkkkkkkkkkkkkkkkkkkk (longtext)])\n" +
			"",
	},
	{
		Query: `
-- cycle 1b
SELECT i_price, i_name, i_data FROM item2 WHERE i_id = 2532`,
		ExpectedPlan: "Project\n" +
			" ├─ columns: [item2.i_price:2, item2.i_name:1, item2.i_data:3]\n" +
			" └─ IndexedTableAccess(item2)\n" +
			"     ├─ index: [item2.i_id]\n" +
			"     ├─ static: [{[2532, 2532]}]\n" +
			"     ├─ colSet: (1-5)\n" +
			"     ├─ tableId: 1\n" +
			"     └─ Table\n" +
			"         ├─ name: item2\n" +
			"         └─ columns: [i_id i_name i_price i_data]\n" +
			"",
		ExpectedEstimates: "Project\n" +
			" ├─ columns: [item2.i_price, item2.i_name, item2.i_data]\n" +
			" └─ IndexedTableAccess(item2)\n" +
			"     ├─ index: [item2.i_id]\n" +
			"     ├─ filters: [{[2532, 2532]}]\n" +
			"     └─ columns: [i_id i_name i_price i_data]\n" +
			"",
		ExpectedAnalysis: "Project\n" +
			" ├─ columns: [item2.i_price, item2.i_name, item2.i_data]\n" +
			" └─ IndexedTableAccess(item2)\n" +
			"     ├─ index: [item2.i_id]\n" +
			"     ├─ filters: [{[2532, 2532]}]\n" +
			"     └─ columns: [i_id i_name i_price i_data]\n" +
			"",
	},
	{
		Query: `SELECT s_quantity, s_data, s_dist_09 s_dist FROM stock2 WHERE s_i_id = 2532 AND s_w_id= 1 FOR UPDATE`,
		ExpectedPlan: "Project\n" +
			" ├─ columns: [stock2.s_quantity:2, stock2.s_data:4, stock2.s_dist_09:3->s_dist:0]\n" +
			" └─ IndexedTableAccess(stock2)\n" +
			"     ├─ index: [stock2.s_w_id,stock2.s_i_id]\n" +
			"     ├─ static: [{[1, 1], [2532, 2532]}]\n" +
			"     ├─ colSet: (1-17)\n" +
			"     ├─ tableId: 1\n" +
			"     └─ Table\n" +
			"         ├─ name: stock2\n" +
			"         └─ columns: [s_i_id s_w_id s_quantity s_dist_09 s_data]\n" +
			"",
		ExpectedEstimates: "Project\n" +
			" ├─ columns: [stock2.s_quantity, stock2.s_data, stock2.s_dist_09 as s_dist]\n" +
			" └─ IndexedTableAccess(stock2)\n" +
			"     ├─ index: [stock2.s_w_id,stock2.s_i_id]\n" +
			"     ├─ filters: [{[1, 1], [2532, 2532]}]\n" +
			"     └─ columns: [s_i_id s_w_id s_quantity s_dist_09 s_data]\n" +
			"",
		ExpectedAnalysis: "Project\n" +
			" ├─ columns: [stock2.s_quantity, stock2.s_data, stock2.s_dist_09 as s_dist]\n" +
			" └─ IndexedTableAccess(stock2)\n" +
			"     ├─ index: [stock2.s_w_id,stock2.s_i_id]\n" +
			"     ├─ filters: [{[1, 1], [2532, 2532]}]\n" +
			"     └─ columns: [s_i_id s_w_id s_quantity s_dist_09 s_data]\n" +
			"",
	},
	{
		Query: `UPDATE stock2 SET s_quantity = 5 WHERE s_i_id = 64568 AND s_w_id= 1`,
		ExpectedPlan: "Update\n" +
			" └─ UpdateSource(SET stock2.s_quantity:2 = 5 (tinyint))\n" +
			"     └─ IndexedTableAccess(stock2)\n" +
			"         ├─ index: [stock2.s_w_id,stock2.s_i_id]\n" +
			"         ├─ static: [{[1, 1], [64568, 64568]}]\n" +
			"         ├─ colSet: (1-17)\n" +
			"         ├─ tableId: 1\n" +
			"         └─ Table\n" +
			"             ├─ name: stock2\n" +
			"             └─ columns: [s_i_id s_w_id s_quantity s_dist_01 s_dist_02 s_dist_03 s_dist_04 s_dist_05 s_dist_06 s_dist_07 s_dist_08 s_dist_09 s_dist_10 s_ytd s_order_cnt s_remote_cnt s_data]\n" +
			"",
	},
	{
		Query: `INSERT INTO order_line2 (ol_o_id, ol_d_id, ol_w_id, ol_number, ol_i_id, ol_supply_w_id, ol_quantity, ol_amount, ol_dist_info) VALUES (
3001,9,1,11,64568,1,7,298,'oooooooooooooooooooooooo')`,
		ExpectedPlan: "Insert(ol_o_id, ol_d_id, ol_w_id, ol_number, ol_i_id, ol_supply_w_id, ol_quantity, ol_amount, ol_dist_info)\n" +
			" ├─ InsertDestination\n" +
			" │   └─ ProcessTable\n" +
			" │       └─ Table\n" +
			" │           ├─ name: order_line2\n" +
			" │           └─ columns: [ol_o_id ol_d_id ol_w_id ol_number ol_i_id ol_supply_w_id ol_delivery_d ol_quantity ol_amount ol_dist_info]\n" +
			" └─ Project\n" +
			"     ├─ columns: [ol_o_id:0!null, ol_d_id:1!null, ol_w_id:2!null, ol_number:3!null, ol_i_id:4, ol_supply_w_id:5, , ol_quantity:6, ol_amount:7, ol_dist_info:8]\n" +
			"     └─ Values([3001 (smallint),9 (tinyint),1 (tinyint),11 (tinyint),64568 (smallint unsigned),1 (tinyint),7 (tinyint),298 (smallint),oooooooooooooooooooooooo (longtext)])\n" +
			"",
	},
	{
		Query: `
-- cycle 2
UPDATE warehouse2 SET w_ytd = w_ytd + 1767 WHERE w_id = 1`,
		ExpectedPlan: "Update\n" +
			" └─ UpdateSource(SET warehouse2.w_ytd:8 = (warehouse2.w_ytd:8 + 1767 (smallint)))\n" +
			"     └─ IndexedTableAccess(warehouse2)\n" +
			"         ├─ index: [warehouse2.w_id]\n" +
			"         ├─ static: [{[1, 1]}]\n" +
			"         ├─ colSet: (1-9)\n" +
			"         ├─ tableId: 1\n" +
			"         └─ Table\n" +
			"             ├─ name: warehouse2\n" +
			"             └─ columns: [w_id w_name w_street_1 w_street_2 w_city w_state w_zip w_tax w_ytd]\n" +
			"",
	},
	{
		Query: `SELECT w_street_1, w_street_2, w_city, w_state, w_zip, w_name FROM warehouse2 WHERE w_id = 1`,
		ExpectedPlan: "Project\n" +
			" ├─ columns: [warehouse2.w_street_1:2, warehouse2.w_street_2:3, warehouse2.w_city:4, warehouse2.w_state:5, warehouse2.w_zip:6, warehouse2.w_name:1]\n" +
			" └─ IndexedTableAccess(warehouse2)\n" +
			"     ├─ index: [warehouse2.w_id]\n" +
			"     ├─ static: [{[1, 1]}]\n" +
			"     ├─ colSet: (1-9)\n" +
			"     ├─ tableId: 1\n" +
			"     └─ Table\n" +
			"         ├─ name: warehouse2\n" +
			"         └─ columns: [w_id w_name w_street_1 w_street_2 w_city w_state w_zip]\n" +
			"",
		ExpectedEstimates: "Project\n" +
			" ├─ columns: [warehouse2.w_street_1, warehouse2.w_street_2, warehouse2.w_city, warehouse2.w_state, warehouse2.w_zip, warehouse2.w_name]\n" +
			" └─ IndexedTableAccess(warehouse2)\n" +
			"     ├─ index: [warehouse2.w_id]\n" +
			"     ├─ filters: [{[1, 1]}]\n" +
			"     └─ columns: [w_id w_name w_street_1 w_street_2 w_city w_state w_zip]\n" +
			"",
		ExpectedAnalysis: "Project\n" +
			" ├─ columns: [warehouse2.w_street_1, warehouse2.w_street_2, warehouse2.w_city, warehouse2.w_state, warehouse2.w_zip, warehouse2.w_name]\n" +
			" └─ IndexedTableAccess(warehouse2)\n" +
			"     ├─ index: [warehouse2.w_id]\n" +
			"     ├─ filters: [{[1, 1]}]\n" +
			"     └─ columns: [w_id w_name w_street_1 w_street_2 w_city w_state w_zip]\n" +
			"",
	},
	{
		Query: `UPDATE district2 SET d_ytd = d_ytd + 1767 WHERE d_w_id = 1 AND d_id= 8`,
		ExpectedPlan: "Update\n" +
			" └─ UpdateSource(SET district2.d_ytd:9 = (district2.d_ytd:9 + 1767 (smallint)))\n" +
			"     └─ IndexedTableAccess(district2)\n" +
			"         ├─ index: [district2.d_w_id,district2.d_id]\n" +
			"         ├─ static: [{[1, 1], [8, 8]}]\n" +
			"         ├─ colSet: (1-11)\n" +
			"         ├─ tableId: 1\n" +
			"         └─ Table\n" +
			"             ├─ name: district2\n" +
			"             └─ columns: [d_id d_w_id d_name d_street_1 d_street_2 d_city d_state d_zip d_tax d_ytd d_next_o_id]\n" +
			"",
	},
	{
		Query: `SELECT d_street_1, d_street_2, d_city, d_state, d_zip, d_name FROM district2 WHERE d_w_id = 1 AND d_id = 8`,
		ExpectedPlan: "Project\n" +
			" ├─ columns: [district2.d_street_1:3, district2.d_street_2:4, district2.d_city:5, district2.d_state:6, district2.d_zip:7, district2.d_name:2]\n" +
			" └─ IndexedTableAccess(district2)\n" +
			"     ├─ index: [district2.d_w_id,district2.d_id]\n" +
			"     ├─ static: [{[1, 1], [8, 8]}]\n" +
			"     ├─ colSet: (1-11)\n" +
			"     ├─ tableId: 1\n" +
			"     └─ Table\n" +
			"         ├─ name: district2\n" +
			"         └─ columns: [d_id d_w_id d_name d_street_1 d_street_2 d_city d_state d_zip]\n" +
			"",
		ExpectedEstimates: "Project\n" +
			" ├─ columns: [district2.d_street_1, district2.d_street_2, district2.d_city, district2.d_state, district2.d_zip, district2.d_name]\n" +
			" └─ IndexedTableAccess(district2)\n" +
			"     ├─ index: [district2.d_w_id,district2.d_id]\n" +
			"     ├─ filters: [{[1, 1], [8, 8]}]\n" +
			"     └─ columns: [d_id d_w_id d_name d_street_1 d_street_2 d_city d_state d_zip]\n" +
			"",
		ExpectedAnalysis: "Project\n" +
			" ├─ columns: [district2.d_street_1, district2.d_street_2, district2.d_city, district2.d_state, district2.d_zip, district2.d_name]\n" +
			" └─ IndexedTableAccess(district2)\n" +
			"     ├─ index: [district2.d_w_id,district2.d_id]\n" +
			"     ├─ filters: [{[1, 1], [8, 8]}]\n" +
			"     └─ columns: [d_id d_w_id d_name d_street_1 d_street_2 d_city d_state d_zip]\n" +
			"",
	},
	{
		Query: `SELECT count(c_id) namecnt FROM customer2 WHERE c_w_id = 1 AND c_d_id= 5 AND c_last='ESEEINGABLE'`,
		ExpectedPlan: "Project\n" +
			" ├─ columns: [count(customer2.c_id):0!null->namecnt:0]\n" +
			" └─ GroupBy\n" +
			"     ├─ select: COUNT(customer2.c_id:0!null)\n" +
			"     ├─ group: \n" +
			"     └─ IndexedTableAccess(customer2)\n" +
			"         ├─ index: [customer2.c_w_id,customer2.c_d_id,customer2.c_last,customer2.c_first]\n" +
			"         ├─ static: [{[1, 1], [5, 5], [ESEEINGABLE, ESEEINGABLE], [NULL, ∞)}]\n" +
			"         ├─ colSet: (1-21)\n" +
			"         ├─ tableId: 1\n" +
			"         └─ Table\n" +
			"             ├─ name: customer2\n" +
			"             └─ columns: [c_id c_d_id c_w_id c_last]\n" +
			"",
		ExpectedEstimates: "Project\n" +
			" ├─ columns: [count(customer2.c_id) as namecnt]\n" +
			" └─ GroupBy\n" +
			"     ├─ select: COUNT(customer2.c_id)\n" +
			"     ├─ group: \n" +
			"     └─ IndexedTableAccess(customer2)\n" +
			"         ├─ index: [customer2.c_w_id,customer2.c_d_id,customer2.c_last,customer2.c_first]\n" +
			"         ├─ filters: [{[1, 1], [5, 5], [ESEEINGABLE, ESEEINGABLE], [NULL, ∞)}]\n" +
			"         └─ columns: [c_id c_d_id c_w_id c_last]\n" +
			"",
		ExpectedAnalysis: "Project\n" +
			" ├─ columns: [count(customer2.c_id) as namecnt]\n" +
			" └─ GroupBy\n" +
			"     ├─ select: COUNT(customer2.c_id)\n" +
			"     ├─ group: \n" +
			"     └─ IndexedTableAccess(customer2)\n" +
			"         ├─ index: [customer2.c_w_id,customer2.c_d_id,customer2.c_last,customer2.c_first]\n" +
			"         ├─ filters: [{[1, 1], [5, 5], [ESEEINGABLE, ESEEINGABLE], [NULL, ∞)}]\n" +
			"         └─ columns: [c_id c_d_id c_w_id c_last]\n" +
			"",
	},
	{
		Query: `SELECT c_id FROM customer2 WHERE c_w_id = 1 AND c_d_id= 5 AND c_last='ESEEINGABLE' ORDER BY c_first`,
		ExpectedPlan: "Project\n" +
			" ├─ columns: [customer2.c_id:0!null]\n" +
			" └─ Sort(customer2.c_first:3 ASC nullsFirst)\n" +
			"     └─ IndexedTableAccess(customer2)\n" +
			"         ├─ index: [customer2.c_w_id,customer2.c_d_id,customer2.c_last,customer2.c_first]\n" +
			"         ├─ static: [{[1, 1], [5, 5], [ESEEINGABLE, ESEEINGABLE], [NULL, ∞)}]\n" +
			"         ├─ colSet: (1-21)\n" +
			"         ├─ tableId: 1\n" +
			"         └─ Table\n" +
			"             ├─ name: customer2\n" +
			"             └─ columns: [c_id c_d_id c_w_id c_first c_last]\n" +
			"",
		ExpectedEstimates: "Project\n" +
			" ├─ columns: [customer2.c_id]\n" +
			" └─ Sort(customer2.c_first ASC)\n" +
			"     └─ IndexedTableAccess(customer2)\n" +
			"         ├─ index: [customer2.c_w_id,customer2.c_d_id,customer2.c_last,customer2.c_first]\n" +
			"         ├─ filters: [{[1, 1], [5, 5], [ESEEINGABLE, ESEEINGABLE], [NULL, ∞)}]\n" +
			"         └─ columns: [c_id c_d_id c_w_id c_first c_last]\n" +
			"",
		ExpectedAnalysis: "Project\n" +
			" ├─ columns: [customer2.c_id]\n" +
			" └─ Sort(customer2.c_first ASC)\n" +
			"     └─ IndexedTableAccess(customer2)\n" +
			"         ├─ index: [customer2.c_w_id,customer2.c_d_id,customer2.c_last,customer2.c_first]\n" +
			"         ├─ filters: [{[1, 1], [5, 5], [ESEEINGABLE, ESEEINGABLE], [NULL, ∞)}]\n" +
			"         └─ columns: [c_id c_d_id c_w_id c_first c_last]\n" +
			"",
	},
	{
		Query: `SELECT c_first, c_middle, c_last, c_street_1, c_street_2, c_city, c_state, c_zip, c_phone, c_credit, c_credit_lim, c_discount, c_balance, c_ytd_payment, c_since FROM customer2 WHERE c_w_id = 1 AND c_d_id= 5 AND c_id=1838 FOR UPDATE`,
		ExpectedPlan: "Project\n" +
			" ├─ columns: [customer2.c_first:3, customer2.c_middle:4, customer2.c_last:5, customer2.c_street_1:6, customer2.c_street_2:7, customer2.c_city:8, customer2.c_state:9, customer2.c_zip:10, customer2.c_phone:11, customer2.c_credit:13, customer2.c_credit_lim:14, customer2.c_discount:15, customer2.c_balance:16, customer2.c_ytd_payment:17, customer2.c_since:12]\n" +
			" └─ IndexedTableAccess(customer2)\n" +
			"     ├─ index: [customer2.c_w_id,customer2.c_d_id,customer2.c_id]\n" +
			"     ├─ static: [{[1, 1], [5, 5], [1838, 1838]}]\n" +
			"     ├─ colSet: (1-21)\n" +
			"     ├─ tableId: 1\n" +
			"     └─ Table\n" +
			"         ├─ name: customer2\n" +
			"         └─ columns: [c_id c_d_id c_w_id c_first c_middle c_last c_street_1 c_street_2 c_city c_state c_zip c_phone c_since c_credit c_credit_lim c_discount c_balance c_ytd_payment]\n" +
			"",
		ExpectedEstimates: "Project\n" +
			" ├─ columns: [customer2.c_first, customer2.c_middle, customer2.c_last, customer2.c_street_1, customer2.c_street_2, customer2.c_city, customer2.c_state, customer2.c_zip, customer2.c_phone, customer2.c_credit, customer2.c_credit_lim, customer2.c_discount, customer2.c_balance, customer2.c_ytd_payment, customer2.c_since]\n" +
			" └─ IndexedTableAccess(customer2)\n" +
			"     ├─ index: [customer2.c_w_id,customer2.c_d_id,customer2.c_id]\n" +
			"     ├─ filters: [{[1, 1], [5, 5], [1838, 1838]}]\n" +
			"     └─ columns: [c_id c_d_id c_w_id c_first c_middle c_last c_street_1 c_street_2 c_city c_state c_zip c_phone c_since c_credit c_credit_lim c_discount c_balance c_ytd_payment]\n" +
			"",
		ExpectedAnalysis: "Project\n" +
			" ├─ columns: [customer2.c_first, customer2.c_middle, customer2.c_last, customer2.c_street_1, customer2.c_street_2, customer2.c_city, customer2.c_state, customer2.c_zip, customer2.c_phone, customer2.c_credit, customer2.c_credit_lim, customer2.c_discount, customer2.c_balance, customer2.c_ytd_payment, customer2.c_since]\n" +
			" └─ IndexedTableAccess(customer2)\n" +
			"     ├─ index: [customer2.c_w_id,customer2.c_d_id,customer2.c_id]\n" +
			"     ├─ filters: [{[1, 1], [5, 5], [1838, 1838]}]\n" +
			"     └─ columns: [c_id c_d_id c_w_id c_first c_middle c_last c_street_1 c_street_2 c_city c_state c_zip c_phone c_since c_credit c_credit_lim c_discount c_balance c_ytd_payment]\n" +
			"",
	},
	{
		Query: `UPDATE customer2 SET c_balance=-1777.000000, c_ytd_payment=1777.000000 WHERE c_w_id = 1 AND c_d_id=5 AND c_id=1838`,
		ExpectedPlan: "Update\n" +
			" └─ UpdateSource(SET customer2.c_balance:16 = -1777.000000,SET customer2.c_ytd_payment:17 = 1777.000000 (decimal(10,6)))\n" +
			"     └─ IndexedTableAccess(customer2)\n" +
			"         ├─ index: [customer2.c_w_id,customer2.c_d_id,customer2.c_id]\n" +
			"         ├─ static: [{[1, 1], [5, 5], [1838, 1838]}]\n" +
			"         ├─ colSet: (1-21)\n" +
			"         ├─ tableId: 1\n" +
			"         └─ Table\n" +
			"             ├─ name: customer2\n" +
			"             └─ columns: [c_id c_d_id c_w_id c_first c_middle c_last c_street_1 c_street_2 c_city c_state c_zip c_phone c_since c_credit c_credit_lim c_discount c_balance c_ytd_payment c_payment_cnt c_delivery_cnt c_data]\n" +
			"",
	},
	{
		Query: `INSERT INTO history2 (h_c_d_id, h_c_w_id, h_c_id, h_d_id, h_w_id, h_date, h_amount, h_data) VALUES (5,1,1838,8,1,NOW(),1767,'name-rqojn name-dnvgs ')`,
		ExpectedPlan: "Insert(h_c_d_id, h_c_w_id, h_c_id, h_d_id, h_w_id, h_date, h_amount, h_data)\n" +
			" ├─ InsertDestination\n" +
			" │   └─ ProcessTable\n" +
			" │       └─ Table\n" +
			" │           ├─ name: history2\n" +
			" │           └─ columns: [h_c_id h_c_d_id h_c_w_id h_d_id h_w_id h_date h_amount h_data]\n" +
			" └─ Project\n" +
			"     ├─ columns: [h_c_id:2, h_c_d_id:0, h_c_w_id:1, h_d_id:3, h_w_id:4, h_date:5, h_amount:6, h_data:7]\n" +
			"     └─ Values([5 (tinyint),1 (tinyint),1838 (smallint),8 (tinyint),1 (tinyint),NOW(),1767 (smallint),name-rqojn name-dnvgs  (longtext)])\n" +
			"",
	},
	{
		Query: `
-- cycle 3
SELECT count(c_id) namecnt FROM customer2 WHERE c_w_id = 1 AND c_d_id= 1 AND c_last='PRIESEPRES'`,
		ExpectedPlan: "Project\n" +
			" ├─ columns: [count(customer2.c_id):0!null->namecnt:0]\n" +
			" └─ GroupBy\n" +
			"     ├─ select: COUNT(customer2.c_id:0!null)\n" +
			"     ├─ group: \n" +
			"     └─ IndexedTableAccess(customer2)\n" +
			"         ├─ index: [customer2.c_w_id,customer2.c_d_id,customer2.c_last,customer2.c_first]\n" +
			"         ├─ static: [{[1, 1], [1, 1], [PRIESEPRES, PRIESEPRES], [NULL, ∞)}]\n" +
			"         ├─ colSet: (1-21)\n" +
			"         ├─ tableId: 1\n" +
			"         └─ Table\n" +
			"             ├─ name: customer2\n" +
			"             └─ columns: [c_id c_d_id c_w_id c_last]\n" +
			"",
		ExpectedEstimates: "Project\n" +
			" ├─ columns: [count(customer2.c_id) as namecnt]\n" +
			" └─ GroupBy\n" +
			"     ├─ select: COUNT(customer2.c_id)\n" +
			"     ├─ group: \n" +
			"     └─ IndexedTableAccess(customer2)\n" +
			"         ├─ index: [customer2.c_w_id,customer2.c_d_id,customer2.c_last,customer2.c_first]\n" +
			"         ├─ filters: [{[1, 1], [1, 1], [PRIESEPRES, PRIESEPRES], [NULL, ∞)}]\n" +
			"         └─ columns: [c_id c_d_id c_w_id c_last]\n" +
			"",
		ExpectedAnalysis: "Project\n" +
			" ├─ columns: [count(customer2.c_id) as namecnt]\n" +
			" └─ GroupBy\n" +
			"     ├─ select: COUNT(customer2.c_id)\n" +
			"     ├─ group: \n" +
			"     └─ IndexedTableAccess(customer2)\n" +
			"         ├─ index: [customer2.c_w_id,customer2.c_d_id,customer2.c_last,customer2.c_first]\n" +
			"         ├─ filters: [{[1, 1], [1, 1], [PRIESEPRES, PRIESEPRES], [NULL, ∞)}]\n" +
			"         └─ columns: [c_id c_d_id c_w_id c_last]\n" +
			"",
	},
	{
		Query: `SELECT c_balance, c_first, c_middle, c_id FROM customer2 WHERE c_w_id = 1 AND c_d_id= 1 AND c_last='PRIESEPRES' ORDER BY c_first`,
		ExpectedPlan: "Project\n" +
			" ├─ columns: [customer2.c_balance:6, customer2.c_first:3, customer2.c_middle:4, customer2.c_id:0!null]\n" +
			" └─ Sort(customer2.c_first:3 ASC nullsFirst)\n" +
			"     └─ IndexedTableAccess(customer2)\n" +
			"         ├─ index: [customer2.c_w_id,customer2.c_d_id,customer2.c_last,customer2.c_first]\n" +
			"         ├─ static: [{[1, 1], [1, 1], [PRIESEPRES, PRIESEPRES], [NULL, ∞)}]\n" +
			"         ├─ colSet: (1-21)\n" +
			"         ├─ tableId: 1\n" +
			"         └─ Table\n" +
			"             ├─ name: customer2\n" +
			"             └─ columns: [c_id c_d_id c_w_id c_first c_middle c_last c_balance]\n" +
			"",
		ExpectedEstimates: "Project\n" +
			" ├─ columns: [customer2.c_balance, customer2.c_first, customer2.c_middle, customer2.c_id]\n" +
			" └─ Sort(customer2.c_first ASC)\n" +
			"     └─ IndexedTableAccess(customer2)\n" +
			"         ├─ index: [customer2.c_w_id,customer2.c_d_id,customer2.c_last,customer2.c_first]\n" +
			"         ├─ filters: [{[1, 1], [1, 1], [PRIESEPRES, PRIESEPRES], [NULL, ∞)}]\n" +
			"         └─ columns: [c_id c_d_id c_w_id c_first c_middle c_last c_balance]\n" +
			"",
		ExpectedAnalysis: "Project\n" +
			" ├─ columns: [customer2.c_balance, customer2.c_first, customer2.c_middle, customer2.c_id]\n" +
			" └─ Sort(customer2.c_first ASC)\n" +
			"     └─ IndexedTableAccess(customer2)\n" +
			"         ├─ index: [customer2.c_w_id,customer2.c_d_id,customer2.c_last,customer2.c_first]\n" +
			"         ├─ filters: [{[1, 1], [1, 1], [PRIESEPRES, PRIESEPRES], [NULL, ∞)}]\n" +
			"         └─ columns: [c_id c_d_id c_w_id c_first c_middle c_last c_balance]\n" +
			"",
	},
	{
		Query: `SELECT o_id, o_carrier_id, o_entry_d FROM orders2 WHERE o_w_id = 1 AND o_d_id = 1 AND o_c_id = 355 ORDER BY o_id DESC`,
		ExpectedPlan: "Project\n" +
			" ├─ columns: [orders2.o_id:0!null, orders2.o_carrier_id:5, orders2.o_entry_d:4]\n" +
			" └─ Sort(orders2.o_id:0!null DESC nullsFirst)\n" +
			"     └─ IndexedTableAccess(orders2)\n" +
			"         ├─ index: [orders2.o_w_id,orders2.o_d_id,orders2.o_c_id,orders2.o_id]\n" +
			"         ├─ static: [{[1, 1], [1, 1], [355, 355], [NULL, ∞)}]\n" +
			"         ├─ colSet: (1-8)\n" +
			"         ├─ tableId: 1\n" +
			"         └─ Table\n" +
			"             ├─ name: orders2\n" +
			"             └─ columns: [o_id o_d_id o_w_id o_c_id o_entry_d o_carrier_id]\n" +
			"",
		ExpectedEstimates: "Project\n" +
			" ├─ columns: [orders2.o_id, orders2.o_carrier_id, orders2.o_entry_d]\n" +
			" └─ Sort(orders2.o_id DESC)\n" +
			"     └─ IndexedTableAccess(orders2)\n" +
			"         ├─ index: [orders2.o_w_id,orders2.o_d_id,orders2.o_c_id,orders2.o_id]\n" +
			"         ├─ filters: [{[1, 1], [1, 1], [355, 355], [NULL, ∞)}]\n" +
			"         └─ columns: [o_id o_d_id o_w_id o_c_id o_entry_d o_carrier_id]\n" +
			"",
		ExpectedAnalysis: "Project\n" +
			" ├─ columns: [orders2.o_id, orders2.o_carrier_id, orders2.o_entry_d]\n" +
			" └─ Sort(orders2.o_id DESC)\n" +
			"     └─ IndexedTableAccess(orders2)\n" +
			"         ├─ index: [orders2.o_w_id,orders2.o_d_id,orders2.o_c_id,orders2.o_id]\n" +
			"         ├─ filters: [{[1, 1], [1, 1], [355, 355], [NULL, ∞)}]\n" +
			"         └─ columns: [o_id o_d_id o_w_id o_c_id o_entry_d o_carrier_id]\n" +
			"",
	},
	{
		Query: `SELECT ol_i_id, ol_supply_w_id, ol_quantity, ol_amount, ol_delivery_d FROM order_line2 WHERE ol_w_id = 1 AND ol_d_id = 1 AND ol_o_id = 1`,
		ExpectedPlan: "Project\n" +
			" ├─ columns: [order_line2.ol_i_id:3, order_line2.ol_supply_w_id:4, order_line2.ol_quantity:6, order_line2.ol_amount:7, order_line2.ol_delivery_d:5]\n" +
			" └─ IndexedTableAccess(order_line2)\n" +
			"     ├─ index: [order_line2.ol_w_id,order_line2.ol_d_id,order_line2.ol_o_id,order_line2.ol_number]\n" +
			"     ├─ static: [{[1, 1], [1, 1], [1, 1], [NULL, ∞)}]\n" +
			"     ├─ colSet: (1-10)\n" +
			"     ├─ tableId: 1\n" +
			"     └─ Table\n" +
			"         ├─ name: order_line2\n" +
			"         └─ columns: [ol_o_id ol_d_id ol_w_id ol_i_id ol_supply_w_id ol_delivery_d ol_quantity ol_amount]\n" +
			"",
		ExpectedEstimates: "Project\n" +
			" ├─ columns: [order_line2.ol_i_id, order_line2.ol_supply_w_id, order_line2.ol_quantity, order_line2.ol_amount, order_line2.ol_delivery_d]\n" +
			" └─ IndexedTableAccess(order_line2)\n" +
			"     ├─ index: [order_line2.ol_w_id,order_line2.ol_d_id,order_line2.ol_o_id,order_line2.ol_number]\n" +
			"     ├─ filters: [{[1, 1], [1, 1], [1, 1], [NULL, ∞)}]\n" +
			"     └─ columns: [ol_o_id ol_d_id ol_w_id ol_i_id ol_supply_w_id ol_delivery_d ol_quantity ol_amount]\n" +
			"",
		ExpectedAnalysis: "Project\n" +
			" ├─ columns: [order_line2.ol_i_id, order_line2.ol_supply_w_id, order_line2.ol_quantity, order_line2.ol_amount, order_line2.ol_delivery_d]\n" +
			" └─ IndexedTableAccess(order_line2)\n" +
			"     ├─ index: [order_line2.ol_w_id,order_line2.ol_d_id,order_line2.ol_o_id,order_line2.ol_number]\n" +
			"     ├─ filters: [{[1, 1], [1, 1], [1, 1], [NULL, ∞)}]\n" +
			"     └─ columns: [ol_o_id ol_d_id ol_w_id ol_i_id ol_supply_w_id ol_delivery_d ol_quantity ol_amount]\n" +
			"",
	},
	{
		Query: `
-- cycle 4
SELECT d_next_o_id FROM district2 WHERE d_id = 5 AND d_w_id= 1`,
		ExpectedPlan: "Project\n" +
			" ├─ columns: [district2.d_next_o_id:2]\n" +
			" └─ IndexedTableAccess(district2)\n" +
			"     ├─ index: [district2.d_w_id,district2.d_id]\n" +
			"     ├─ static: [{[1, 1], [5, 5]}]\n" +
			"     ├─ colSet: (1-11)\n" +
			"     ├─ tableId: 1\n" +
			"     └─ Table\n" +
			"         ├─ name: district2\n" +
			"         └─ columns: [d_id d_w_id d_next_o_id]\n" +
			"",
		ExpectedEstimates: "Project\n" +
			" ├─ columns: [district2.d_next_o_id]\n" +
			" └─ IndexedTableAccess(district2)\n" +
			"     ├─ index: [district2.d_w_id,district2.d_id]\n" +
			"     ├─ filters: [{[1, 1], [5, 5]}]\n" +
			"     └─ columns: [d_id d_w_id d_next_o_id]\n" +
			"",
		ExpectedAnalysis: "Project\n" +
			" ├─ columns: [district2.d_next_o_id]\n" +
			" └─ IndexedTableAccess(district2)\n" +
			"     ├─ index: [district2.d_w_id,district2.d_id]\n" +
			"     ├─ filters: [{[1, 1], [5, 5]}]\n" +
			"     └─ columns: [d_id d_w_id d_next_o_id]\n" +
			"",
	},
	{
		Query: `SELECT COUNT(DISTINCT (s_i_id)) FROM order_line2, stock2 WHERE ol_w_id = 1 AND ol_d_id = 5 AND ol_o_id < 3003 AND ol_o_id >= 2983 AND s_w_id= 1 AND s_i_id=ol_i_id AND s_quantity < 18`,
		ExpectedPlan: "Project\n" +
			" ├─ columns: [countdistinct([stock2.s_i_id]):0!null->COUNT(DISTINCT (s_i_id)):0]\n" +
			" └─ GroupBy\n" +
			"     ├─ select: COUNTDISTINCT([stock2.s_i_id])\n" +
			"     ├─ group: \n" +
			"     └─ LookupJoin\n" +
			"         ├─ IndexedTableAccess(order_line2)\n" +
			"         │   ├─ index: [order_line2.ol_w_id,order_line2.ol_d_id,order_line2.ol_o_id,order_line2.ol_number]\n" +
			"         │   ├─ static: [{[1, 1], [5, 5], [2983, 3003), [NULL, ∞)}]\n" +
			"         │   ├─ colSet: (1-10)\n" +
			"         │   ├─ tableId: 1\n" +
			"         │   └─ Table\n" +
			"         │       ├─ name: order_line2\n" +
			"         │       └─ columns: [ol_o_id ol_d_id ol_w_id ol_i_id]\n" +
			"         └─ Filter\n" +
			"             ├─ AND\n" +
			"             │   ├─ Eq\n" +
			"             │   │   ├─ stock2.s_w_id:1!null\n" +
			"             │   │   └─ 1 (smallint)\n" +
			"             │   └─ LessThan\n" +
			"             │       ├─ stock2.s_quantity:2\n" +
			"             │       └─ 18 (smallint)\n" +
			"             └─ IndexedTableAccess(stock2)\n" +
			"                 ├─ index: [stock2.s_w_id,stock2.s_i_id]\n" +
			"                 ├─ keys: [1 (smallint) order_line2.ol_i_id:3]\n" +
			"                 ├─ colSet: (11-27)\n" +
			"                 ├─ tableId: 2\n" +
			"                 └─ Table\n" +
			"                     ├─ name: stock2\n" +
			"                     └─ columns: [s_i_id s_w_id s_quantity]\n" +
			"",
		ExpectedEstimates: "Project\n" +
			" ├─ columns: [countdistinct([stock2.s_i_id]) as COUNT(DISTINCT (s_i_id))]\n" +
			" └─ GroupBy\n" +
			"     ├─ select: COUNTDISTINCT([stock2.s_i_id])\n" +
			"     ├─ group: \n" +
			"     └─ LookupJoin (estimated cost=130201.500 rows=39455)\n" +
			"         ├─ IndexedTableAccess(order_line2)\n" +
			"         │   ├─ index: [order_line2.ol_w_id,order_line2.ol_d_id,order_line2.ol_o_id,order_line2.ol_number]\n" +
			"         │   ├─ filters: [{[1, 1], [5, 5], [2983, 3003), [NULL, ∞)}]\n" +
			"         │   └─ columns: [ol_o_id ol_d_id ol_w_id ol_i_id]\n" +
			"         └─ Filter\n" +
			"             ├─ ((stock2.s_w_id = 1) AND (stock2.s_quantity < 18))\n" +
			"             └─ IndexedTableAccess(stock2)\n" +
			"                 ├─ index: [stock2.s_w_id,stock2.s_i_id]\n" +
			"                 ├─ columns: [s_i_id s_w_id s_quantity]\n" +
			"                 └─ keys: 1, order_line2.ol_i_id\n" +
			"",
		ExpectedAnalysis: "Project\n" +
			" ├─ columns: [countdistinct([stock2.s_i_id]) as COUNT(DISTINCT (s_i_id))]\n" +
			" └─ GroupBy\n" +
			"     ├─ select: COUNTDISTINCT([stock2.s_i_id])\n" +
			"     ├─ group: \n" +
			"     └─ LookupJoin (estimated cost=130201.500 rows=39455) (actual rows=0 loops=1)\n" +
			"         ├─ IndexedTableAccess(order_line2)\n" +
			"         │   ├─ index: [order_line2.ol_w_id,order_line2.ol_d_id,order_line2.ol_o_id,order_line2.ol_number]\n" +
			"         │   ├─ filters: [{[1, 1], [5, 5], [2983, 3003), [NULL, ∞)}]\n" +
			"         │   └─ columns: [ol_o_id ol_d_id ol_w_id ol_i_id]\n" +
			"         └─ Filter\n" +
			"             ├─ ((stock2.s_w_id = 1) AND (stock2.s_quantity < 18))\n" +
			"             └─ IndexedTableAccess(stock2)\n" +
			"                 ├─ index: [stock2.s_w_id,stock2.s_i_id]\n" +
			"                 ├─ columns: [s_i_id s_w_id s_quantity]\n" +
			"                 └─ keys: 1, order_line2.ol_i_id\n" +
			"",
	},
	{
		Query: `
-- other
SELECT o_id, o_entry_d, COALESCE(o_carrier_id,0)
FROM orders2
WHERE
  o_w_id = 1 AND
  o_d_id = 3 AND
  o_c_id = 20001 AND
  o_id = (SELECT MAX(o_id) FROM orders2 WHERE o_w_id = 1 AND o_d_id = 3 AND o_c_id = 20001)`,
		ExpectedPlan: "Project\n" +
			" ├─ columns: [orders2.o_id:0!null, orders2.o_entry_d:4, coalesce(orders2.o_carrier_id:5,0 (tinyint))->COALESCE(o_carrier_id,0):0]\n" +
			" └─ Filter\n" +
			"     ├─ Eq\n" +
			"     │   ├─ orders2.o_id:0!null\n" +
			"     │   └─ Subquery\n" +
			"     │       ├─ cacheable: true\n" +
			"     │       ├─ alias-string: select MAX(o_id) from orders2 where o_w_id = 1 and o_d_id = 3 and o_c_id = 20001\n" +
			"     │       └─ Project\n" +
			"     │           ├─ columns: [max(orders2.o_id):8!null->MAX(o_id):0]\n" +
			"     │           └─ GroupBy\n" +
			"     │               ├─ select: MAX(orders2.o_id:8!null)\n" +
			"     │               ├─ group: \n" +
			"     │               └─ IndexedTableAccess(orders2)\n" +
			"     │                   ├─ index: [orders2.o_w_id,orders2.o_d_id,orders2.o_c_id,orders2.o_id]\n" +
			"     │                   ├─ static: [{[1, 1], [3, 3], [20001, 20001], [NULL, ∞)}]\n" +
			"     │                   ├─ colSet: (9-16)\n" +
			"     │                   ├─ tableId: 2\n" +
			"     │                   └─ Table\n" +
			"     │                       ├─ name: orders2\n" +
			"     │                       └─ columns: [o_id o_d_id o_w_id o_c_id]\n" +
			"     └─ IndexedTableAccess(orders2)\n" +
			"         ├─ index: [orders2.o_w_id,orders2.o_d_id,orders2.o_c_id,orders2.o_id]\n" +
			"         ├─ static: [{[1, 1], [3, 3], [20001, 20001], [NULL, ∞)}]\n" +
			"         ├─ colSet: (1-8)\n" +
			"         ├─ tableId: 1\n" +
			"         └─ Table\n" +
			"             ├─ name: orders2\n" +
			"             └─ columns: [o_id o_d_id o_w_id o_c_id o_entry_d o_carrier_id o_ol_cnt o_all_local]\n" +
			"",
		ExpectedEstimates: "Project\n" +
			" ├─ columns: [orders2.o_id, orders2.o_entry_d, coalesce(orders2.o_carrier_id,0) as COALESCE(o_carrier_id,0)]\n" +
			" └─ Filter\n" +
			"     ├─ (orders2.o_id = Subquery(select MAX(o_id) from orders2 where o_w_id = 1 and o_d_id = 3 and o_c_id = 20001))\n" +
			"     └─ IndexedTableAccess(orders2)\n" +
			"         ├─ index: [orders2.o_w_id,orders2.o_d_id,orders2.o_c_id,orders2.o_id]\n" +
			"         └─ filters: [{[1, 1], [3, 3], [20001, 20001], [NULL, ∞)}]\n" +
			"",
		ExpectedAnalysis: "Project\n" +
			" ├─ columns: [orders2.o_id, orders2.o_entry_d, coalesce(orders2.o_carrier_id,0) as COALESCE(o_carrier_id,0)]\n" +
			" └─ Filter\n" +
			"     ├─ (orders2.o_id = Subquery(select MAX(o_id) from orders2 where o_w_id = 1 and o_d_id = 3 and o_c_id = 20001))\n" +
			"     └─ IndexedTableAccess(orders2)\n" +
			"         ├─ index: [orders2.o_w_id,orders2.o_d_id,orders2.o_c_id,orders2.o_id]\n" +
			"         └─ filters: [{[1, 1], [3, 3], [20001, 20001], [NULL, ∞)}]\n" +
			"",
	},
	{
		Query: `
select o_id, o.o_d_id
from
  orders2 o,
  (
    select o_c_id, o_w_id, o_d_id, count(distinct o_id)
    from orders2
    where o_w_id=1  and o_id > 2100 and o_id < 11153
    group by o_c_id,o_d_id,o_w_id
    having count( distinct o_id) > 1
    limit 1
  ) t
  where
    t.o_w_id=o.o_w_id and
    t.o_d_id=o.o_d_id and
    t.o_c_id=o.o_c_id
  limit 1;`,
		ExpectedPlan: "Limit(1)\n" +
			" └─ Project\n" +
			"     ├─ columns: [o.o_id:4!null, o.o_d_id:5!null]\n" +
			"     └─ LookupJoin\n" +
			"         ├─ SubqueryAlias\n" +
			"         │   ├─ name: t\n" +
			"         │   ├─ outerVisibility: false\n" +
			"         │   ├─ isLateral: false\n" +
			"         │   ├─ cacheable: true\n" +
			"         │   ├─ colSet: (18-21)\n" +
			"         │   ├─ tableId: 3\n" +
			"         │   └─ Limit(1)\n" +
			"         │       └─ Project\n" +
			"         │           ├─ columns: [orders2.o_c_id:1, orders2.o_w_id:2!null, orders2.o_d_id:3!null, countdistinct([orders2.o_id]):0!null->count(distinct o_id):0]\n" +
			"         │           └─ Having\n" +
			"         │               ├─ GreaterThan\n" +
			"         │               │   ├─ countdistinct([orders2.o_id]):0!null\n" +
			"         │               │   └─ 1 (bigint)\n" +
			"         │               └─ GroupBy\n" +
			"         │                   ├─ select: COUNTDISTINCT([orders2.o_id]), orders2.o_c_id:3, orders2.o_w_id:2!null, orders2.o_d_id:1!null, orders2.o_id:0!null\n" +
			"         │                   ├─ group: orders2.o_c_id:3, orders2.o_d_id:1!null, orders2.o_w_id:2!null\n" +
			"         │                   └─ IndexedTableAccess(orders2)\n" +
			"         │                       ├─ index: [orders2.o_w_id,orders2.o_d_id,orders2.o_id]\n" +
			"         │                       ├─ static: [{[1, 1], [NULL, ∞), (2100, 11153)}]\n" +
			"         │                       ├─ colSet: (9-16)\n" +
			"         │                       ├─ tableId: 2\n" +
			"         │                       └─ Table\n" +
			"         │                           ├─ name: orders2\n" +
			"         │                           └─ columns: [o_id o_d_id o_w_id o_c_id o_entry_d o_carrier_id o_ol_cnt o_all_local]\n" +
			"         └─ TableAlias(o)\n" +
			"             └─ IndexedTableAccess(orders2)\n" +
			"                 ├─ index: [orders2.o_w_id,orders2.o_d_id,orders2.o_c_id,orders2.o_id]\n" +
			"                 ├─ keys: [t.o_w_id:1!null t.o_d_id:2!null t.o_c_id:0]\n" +
			"                 ├─ colSet: (1-8)\n" +
			"                 ├─ tableId: 1\n" +
			"                 └─ Table\n" +
			"                     ├─ name: orders2\n" +
			"                     └─ columns: [o_id o_d_id o_w_id o_c_id]\n" +
			"",
		ExpectedEstimates: "Limit(1)\n" +
			" └─ Project\n" +
			"     ├─ columns: [o.o_id, o.o_d_id]\n" +
			"     └─ LookupJoin\n" +
			"         ├─ SubqueryAlias\n" +
			"         │   ├─ name: t\n" +
			"         │   ├─ outerVisibility: false\n" +
			"         │   ├─ isLateral: false\n" +
			"         │   ├─ cacheable: true\n" +
			"         │   ├─ colSet: (18-21)\n" +
			"         │   ├─ tableId: 3\n" +
			"         │   └─ Limit(1)\n" +
			"         │       └─ Project\n" +
			"         │           ├─ columns: [orders2.o_c_id, orders2.o_w_id, orders2.o_d_id, countdistinct([orders2.o_id]) as count(distinct o_id)]\n" +
			"         │           └─ Having((countdistinct([orders2.o_id]) > 1))\n" +
			"         │               └─ GroupBy\n" +
			"         │                   ├─ select: COUNTDISTINCT([orders2.o_id]), orders2.o_c_id, orders2.o_w_id, orders2.o_d_id, orders2.o_id\n" +
			"         │                   ├─ group: orders2.o_c_id, orders2.o_d_id, orders2.o_w_id\n" +
			"         │                   └─ IndexedTableAccess(orders2)\n" +
			"         │                       ├─ index: [orders2.o_w_id,orders2.o_d_id,orders2.o_id]\n" +
			"         │                       └─ filters: [{[1, 1], [NULL, ∞), (2100, 11153)}]\n" +
			"         └─ TableAlias(o)\n" +
			"             └─ IndexedTableAccess(orders2)\n" +
			"                 ├─ index: [orders2.o_w_id,orders2.o_d_id,orders2.o_c_id,orders2.o_id]\n" +
			"                 ├─ columns: [o_id o_d_id o_w_id o_c_id]\n" +
			"                 └─ keys: t.o_w_id, t.o_d_id, t.o_c_id\n" +
			"",
		ExpectedAnalysis: "Limit(1)\n" +
			" └─ Project\n" +
			"     ├─ columns: [o.o_id, o.o_d_id]\n" +
			"     └─ LookupJoin\n" +
			"         ├─ SubqueryAlias\n" +
			"         │   ├─ name: t\n" +
			"         │   ├─ outerVisibility: false\n" +
			"         │   ├─ isLateral: false\n" +
			"         │   ├─ cacheable: true\n" +
			"         │   ├─ colSet: (18-21)\n" +
			"         │   ├─ tableId: 3\n" +
			"         │   └─ Limit(1)\n" +
			"         │       └─ Project\n" +
			"         │           ├─ columns: [orders2.o_c_id, orders2.o_w_id, orders2.o_d_id, countdistinct([orders2.o_id]) as count(distinct o_id)]\n" +
			"         │           └─ Having((countdistinct([orders2.o_id]) > 1))\n" +
			"         │               └─ GroupBy\n" +
			"         │                   ├─ select: COUNTDISTINCT([orders2.o_id]), orders2.o_c_id, orders2.o_w_id, orders2.o_d_id, orders2.o_id\n" +
			"         │                   ├─ group: orders2.o_c_id, orders2.o_d_id, orders2.o_w_id\n" +
			"         │                   └─ IndexedTableAccess(orders2)\n" +
			"         │                       ├─ index: [orders2.o_w_id,orders2.o_d_id,orders2.o_id]\n" +
			"         │                       └─ filters: [{[1, 1], [NULL, ∞), (2100, 11153)}]\n" +
			"         └─ TableAlias(o)\n" +
			"             └─ IndexedTableAccess(orders2)\n" +
			"                 ├─ index: [orders2.o_w_id,orders2.o_d_id,orders2.o_c_id,orders2.o_id]\n" +
			"                 ├─ columns: [o_id o_d_id o_w_id o_c_id]\n" +
			"                 └─ keys: t.o_w_id, t.o_d_id, t.o_c_id\n" +
			"",
	},
}
