// Code generated by "stringer -type=frameExtent"; DO NOT EDIT.

package support

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[unboundedPreceding-0]
	_ = x[startNPreceding-1]
	_ = x[startCurrentRow-2]
	_ = x[startNFollowing-3]
	_ = x[unknown-4]
	_ = x[endNPreceding-5]
	_ = x[endCurrentRow-6]
	_ = x[endNFollowing-7]
	_ = x[unboundedFollowing-8]
}

const _frameExtent_name = "unboundedPrecedingstartNPrecedingstartCurrentRowstartNFollowingunknownendNPrecedingendCurrentRowendNFollowingunboundedFollowing"

var _frameExtent_index = [...]uint8{0, 18, 33, 48, 63, 70, 83, 96, 109, 127}

func (i frameExtent) String() string {
	if i < 0 || i >= frameExtent(len(_frameExtent_index)-1) {
		return "frameExtent(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _frameExtent_name[_frameExtent_index[i]:_frameExtent_index[i+1]]
}
