// Copyright 2020-2021 Dolthub, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package function

import (
	"math"

	"gopkg.in/src-d/go-errors.v1"

	"github.com/dolthub/go-mysql-server/sql"
	"github.com/dolthub/go-mysql-server/sql/expression/function/aggregation"
	"github.com/dolthub/go-mysql-server/sql/expression/function/aggregation/window"
	"github.com/dolthub/go-mysql-server/sql/expression/function/json"
	"github.com/dolthub/go-mysql-server/sql/expression/function/spatial"
	"github.com/dolthub/go-mysql-server/sql/expression/function/vector"
)

// ErrFunctionAlreadyRegistered is thrown when a function is already registered
var ErrFunctionAlreadyRegistered = errors.NewKind("function '%s' is already registered")

// BuiltIns is the set of built-in functions any integrator can use
var BuiltIns = []sql.Function{
	// elt, find_in_set, insert, load_file, locate
	sql.NewFunction1("abs", NewAbsVal),
	sql.NewFunction1("acos", NewAcos),
	sql.NewFunctionN("adddate", NewAddDate),
	sql.NewFunction1("any_value", func(ctx *sql.Context, e sql.Expression) sql.Expression { return aggregation.NewAnyValue(e) }),
	sql.NewFunction1("ascii", NewAscii),
	sql.NewFunction1("asin", NewAsin),
	sql.NewFunctionN("atan", NewAtan),
	sql.NewFunctionN("atan2", NewAtan),
	sql.NewFunction1("avg", func(ctx *sql.Context, e sql.Expression) sql.Expression { return aggregation.NewAvg(e) }),
	sql.NewFunction1("bin", NewBin),
	sql.NewFunctionN("bin_to_uuid", NewBinToUUID),
	sql.NewFunction1("bit_and", func(ctx *sql.Context, e sql.Expression) sql.Expression { return aggregation.NewBitAnd(e) }),
	sql.NewFunction1("bit_count", NewBitCount),
	sql.NewFunction1("bit_length", NewBitlength),
	sql.NewFunction1("bit_or", func(ctx *sql.Context, e sql.Expression) sql.Expression { return aggregation.NewBitOr(e) }),
	sql.NewFunction1("bit_xor", func(ctx *sql.Context, e sql.Expression) sql.Expression { return aggregation.NewBitXor(e) }),
	sql.NewFunction1("ceil", NewCeil),
	sql.NewFunction1("ceiling", NewCeil),
	sql.NewFunctionN("char", NewChar),
	sql.NewFunction1("charset", NewCharset),
	sql.NewFunction1("char_length", NewCharLength),
	sql.NewFunction1("character_length", NewCharLength),
	sql.NewFunctionN("coalesce", NewCoalesce),
	sql.NewFunction1("coercibility", NewCoercibility),
	sql.NewFunction1("collation", NewCollation),
	sql.NewFunction1("compress", NewCompress),
	sql.NewFunctionN("concat", NewConcat),
	sql.NewFunctionN("concat_ws", NewConcatWithSeparator),
	sql.NewFunction0("connection_id", NewConnectionID),
	sql.NewFunction3("conv", NewConv),
	sql.NewFunction1("cos", NewCos),
	sql.NewFunction1("cot", NewCot),
	sql.NewFunction3("convert_tz", NewConvertTz),
	sql.NewFunction1("count", func(ctx *sql.Context, e sql.Expression) sql.Expression { return aggregation.NewCount(e) }),
	sql.NewFunction1("crc32", NewCrc32),
	sql.NewFunction0("curdate", NewCurrDate),
	sql.NewFunction0("current_date", NewCurrentDate),
	sql.NewFunctionN("current_time", NewCurrTime),
	sql.NewFunctionN("current_timestamp", NewNow),
	sql.NewFunction0("current_user", NewCurrentUser),
	sql.NewFunctionN("curtime", NewCurrTime),
	sql.NewFunction0("database", NewDatabase),
	sql.NewFunction1("date", NewDate),
	sql.NewFunctionN("datetime", NewDatetime),
	sql.NewFunction2("datediff", NewDateDiff),
	sql.NewFunctionN("date_add", NewDateAdd),
	sql.NewFunction2("date_format", NewDateFormat),
	sql.NewFunctionN("date_sub", NewDateSub),
	sql.NewFunction1("day", NewDay),
	sql.NewFunction1("dayname", NewDayName),
	sql.NewFunction1("dayofmonth", NewDay),
	sql.NewFunction1("dayofweek", NewDayOfWeek),
	sql.NewFunction1("dayofyear", NewDayOfYear),
	sql.NewFunction1("degrees", NewDegrees),
	sql.NewFunctionN("elt", NewElt),
	sql.NewFunction1("exp", NewExp),
	sql.NewFunctionN("export_set", NewExportSet),
	sql.NewFunction2("extract", NewExtract),
	sql.NewFunctionN("field", NewField),
	sql.NewFunction2("find_in_set", NewFindInSet),
	sql.NewFunction1("first", func(ctx *sql.Context, e sql.Expression) sql.Expression { return aggregation.NewFirst(e) }),
	sql.NewFunction1("floor", NewFloor),
	sql.NewFunction0("found_rows", NewFoundRows),
	sql.NewFunctionN("format", NewFormat),
	sql.NewFunction1("from_base64", NewFromBase64),
	sql.NewFunction1("from_days", NewFromDays),
	sql.NewFunctionN("from_unixtime", NewFromUnixtime),
	sql.NewFunction2("get_format", NewGetFormat),
	sql.NewFunctionN("greatest", NewGreatest),
	sql.NewFunction0("group_concat", aggregation.NewEmptyGroupConcat),
	sql.NewFunction2("gtid_subtract", NewGtidSubtract),
	sql.NewFunction1("hex", NewHex),
	sql.NewFunction1("hour", NewHour),
	sql.NewFunction3("if", NewIf),
	sql.NewFunction2("ifnull", NewIfNull),
	sql.NewFunction1("inet_aton", NewInetAton),
	sql.NewFunction1("inet_ntoa", NewInetNtoa),
	sql.NewFunction1("inet6_aton", NewInet6Aton),
	sql.NewFunction1("inet6_ntoa", NewInet6Ntoa),
	sql.NewFunction4("insert", NewInsert),
	sql.NewFunction2("instr", NewInstr),
	sql.NewFunction1("is_binary", NewIsBinary),
	sql.NewFunction1("is_ipv4", NewIsIPv4),
	sql.NewFunction1("is_ipv4_compat", NewIsIPv4Compat),
	sql.NewFunction1("is_ipv4_mapped", NewIsIPv4Mapped),
	sql.NewFunction1("is_ipv6", NewIsIPv6),
	sql.NewFunction1("is_uuid", NewIsUUID),
	sql.NewFunction1("isnull", NewIsNull),
	sql.NewFunctionN("json_array", json.NewJSONArray),
	sql.NewFunction1("json_arrayagg", func(ctx *sql.Context, e sql.Expression) sql.Expression { return aggregation.NewJsonArray(e) }),
	sql.NewFunction2("json_objectagg", aggregation.NewJSONObjectAgg),
	sql.NewFunctionN("json_array_append", json.NewJSONArrayAppend),
	sql.NewFunctionN("json_array_insert", json.NewJSONArrayInsert),
	sql.NewFunctionN("json_contains", json.NewJSONContains),
	sql.NewFunctionN("json_contains_path", json.NewJSONContainsPath),
	sql.NewFunctionN("json_depth", json.NewJSONDepth),
	sql.NewFunctionN("json_extract", json.NewJSONExtract),
	sql.NewFunctionN("json_insert", json.NewJSONInsert),
	sql.NewFunctionN("json_keys", json.NewJSONKeys),
	sql.NewFunctionN("json_length", json.NewJsonLength),
	sql.NewFunctionN("json_merge", json.NewJSONMergePreserve),
	sql.NewFunctionN("json_merge_patch", json.NewJSONMergePatch),
	sql.NewFunctionN("json_merge_preserve", json.NewJSONMergePreserve),
	sql.NewFunctionN("json_object", json.NewJSONObject),
	sql.NewFunctionN("json_overlaps", json.NewJSONOverlaps),
	sql.NewFunction1("json_pretty", json.NewJSONPretty),
	sql.NewFunction1("json_quote", json.NewJSONQuote),
	sql.NewFunctionN("json_remove", json.NewJSONRemove),
	sql.NewFunctionN("json_replace", json.NewJSONReplace),
	sql.NewFunctionN("json_schema_valid", json.NewJSONSchemaValid),
	sql.NewFunctionN("json_schema_validation_report", json.NewJSONSchemaValidationReport),
	sql.NewFunctionN("json_search", json.NewJSONSearch),
	sql.NewFunctionN("json_set", json.NewJSONSet),
	sql.NewFunctionN("json_storage_free", json.NewJSONStorageFree),
	sql.NewFunctionN("json_storage_size", json.NewJSONStorageSize),
	sql.NewFunctionN("json_table", json.NewJSONTable),
	sql.NewFunctionN("json_type", json.NewJSONType),
	sql.NewFunction1("json_unquote", json.NewJSONUnquote),
	sql.NewFunctionN("json_valid", json.NewJSONValid),
	sql.NewFunctionN("json_value", json.NewJsonValue),
	sql.NewFunctionN("lag", func(ctx *sql.Context, e ...sql.Expression) (sql.Expression, error) { return window.NewLag(e...) }),
	sql.NewFunction1("last", func(ctx *sql.Context, e sql.Expression) sql.Expression { return aggregation.NewLast(e) }),
	sql.NewFunction1("last_day", NewLastDay),
	sql.NewFunctionN("last_insert_id", NewLastInsertId),
	sql.NewFunctionN("last_insert_uuid", NewLastInsertUuid),
	sql.NewFunction1("lcase", NewLower),
	sql.NewFunctionN("lead", func(ctx *sql.Context, e ...sql.Expression) (sql.Expression, error) { return window.NewLead(e...) }),
	sql.NewFunctionN("least", NewLeast),
	sql.NewFunction2("left", NewLeft),
	sql.NewFunction1("length", NewLength),
	sql.NewFunction1("ln", NewLogBaseFunc(float64(math.E))),
	sql.NewFunction1("load_file", NewLoadFile),
	sql.NewFunctionN("localtime", NewNow),
	sql.NewFunctionN("localtimestamp", NewNow),
	sql.NewFunctionN("locate", NewLocate),
	sql.NewFunctionN("log", NewLog),
	sql.NewFunction1("log10", NewLogBaseFunc(float64(10))),
	sql.NewFunction1("log2", NewLogBaseFunc(float64(2))),
	sql.NewFunction1("lower", NewLower),
	sql.NewFunctionN("lpad", NewLeftPad),
	sql.NewFunction1("ltrim", NewLeftTrim),
	sql.NewFunction2("makedate", NewMakeDate),
	sql.NewFunctionN("make_set", NewMakeSet),
	sql.NewFunction1("max", func(ctx *sql.Context, e sql.Expression) sql.Expression { return aggregation.NewMax(e) }),
	sql.NewFunction1("md5", NewMD5),
	sql.NewFunction1("microsecond", NewMicrosecond),
	sql.NewFunctionN("mid", NewSubstring),
	sql.NewFunction1("min", func(ctx *sql.Context, e sql.Expression) sql.Expression { return aggregation.NewMin(e) }),
	sql.NewFunction1("minute", NewMinute),
	sql.NewFunctionN("mod", NewMod),
	sql.NewFunction1("month", NewMonth),
	sql.NewFunction1("monthname", NewMonthName),
	sql.NewFunction1("ntile", window.NewNTile),
	sql.NewFunctionN("now", NewNow),
	sql.NewFunction2("nullif", NewNullIf),
	sql.NewFunction1("oct", NewOct),
	sql.NewFunction1("octet_length", NewLength),
	sql.NewFunction1("ord", NewOrd),
	sql.NewFunction0("pi", NewPi),
	sql.NewFunction2("pow", NewPower),
	sql.NewFunction2("power", NewPower),
	sql.NewFunction1("quarter", NewQuarter),
	sql.NewFunction1("quote", NewQuote),
	sql.NewFunction1("radians", NewRadians),
	sql.NewFunctionN("rand", NewRand),
	sql.NewFunctionN("regexp_instr", NewRegexpInstr),
	sql.NewFunctionN("regexp_like", NewRegexpLike),
	sql.NewFunctionN("regexp_replace", NewRegexpReplace),
	sql.NewFunctionN("regexp_substr", NewRegexpSubstr),
	sql.NewFunction2("repeat", NewRepeat),
	sql.NewFunction3("replace", NewReplace),
	sql.NewFunction1("reverse", NewReverse),
	sql.NewFunction2("right", NewRight),
	sql.NewFunctionN("round", NewRound),
	sql.NewFunction0("row_count", NewRowCount),
	sql.NewFunction0("row_number", window.NewRowNumber),
	sql.NewFunction0("percent_rank", window.NewPercentRank),
	sql.NewFunction0("rank", window.NewRank),
	sql.NewFunction0("dense_rank", window.NewDenseRank),
	sql.NewFunction1("first_value", window.NewFirstValue),
	sql.NewFunction1("last_value", window.NewLastValue),
	sql.NewFunction1("random_bytes", NewRandomBytes),
	sql.NewFunctionN("rpad", NewRightPad),
	sql.NewFunction1("rtrim", NewRightTrim),
	sql.NewFunction0("schema", NewDatabase),
	sql.NewFunction1("second", NewSecond),
	sql.NewFunction1("sha", NewSHA1),
	sql.NewFunction1("sha1", NewSHA1),
	sql.NewFunction2("sha2", NewSHA2),
	sql.NewFunction1("sign", NewSign),
	sql.NewFunction1("sin", NewSin),
	sql.NewFunction1("sleep", NewSleep),
	sql.NewFunction1("soundex", NewSoundex),
	sql.NewFunction1("sqrt", NewSqrt),
	sql.NewFunction2("str_to_date", NewStrToDate),
	sql.NewFunctionN("subdate", NewSubDate),
	sql.NewFunction2("point", spatial.NewPoint),
	sql.NewFunctionN("linestring", spatial.NewLineString),
	sql.NewFunctionN("polygon", spatial.NewPolygon),
	sql.NewFunctionN("multipoint", spatial.NewMultiPoint),
	sql.NewFunctionN("multilinestring", spatial.NewMultiLineString),
	sql.NewFunctionN("multipolygon", spatial.NewMultiPolygon),
	sql.NewFunctionN("geometrycollection", spatial.NewGeomColl),
	sql.NewFunctionN("geomcollection", spatial.NewGeomColl),
	sql.NewFunction1("space", NewSpace),
	sql.NewFunction1("st_area", spatial.NewArea),
	sql.NewFunction1("st_asbinary", spatial.NewAsWKB),
	sql.NewFunctionN("st_asgeojson", spatial.NewAsGeoJSON),
	sql.NewFunction1("st_aswkb", spatial.NewAsWKB),
	sql.NewFunction1("st_aswkt", spatial.NewAsWKT),
	sql.NewFunction1("st_astext", spatial.NewAsWKT),
	sql.NewFunctionN("st_distance", spatial.NewDistance),
	sql.NewFunction1("st_dimension", spatial.NewDimension),
	sql.NewFunction2("st_disjoint", spatial.NewDisjoint),
	sql.NewFunction1("st_centroid", spatial.NewCentroid),
	sql.NewFunction2("st_contains", spatial.NewContains),
	sql.NewFunction2("st_equal", spatial.NewSTEquals),
	sql.NewFunction2("st_equals", spatial.NewSTEquals),
	sql.NewFunction1("st_endpoint", spatial.NewEndPoint),
	sql.NewFunction1("st_convexhull", spatial.NewConvexHull),
	sql.NewFunction1("st_envelope", spatial.NewEnvelope),
	sql.NewFunction1("st_exteriorring", spatial.NewExteriorRing),
	sql.NewFunctionN("st_geomcollfromtext", spatial.NewGeomCollFromText),
	sql.NewFunctionN("st_geomcollfromtxt", spatial.NewGeomCollFromText),
	sql.NewFunctionN("st_geomcollfromwkb", spatial.NewGeomCollFromWKB),
	sql.NewFunctionN("st_geometrycollectionfromwkb", spatial.NewGeomCollFromWKB),
	sql.NewFunctionN("st_geometrycollectionfromtext", spatial.NewGeomCollFromText),
	sql.NewFunction2("st_geometryn", spatial.NewGeometryN),
	sql.NewFunction1("st_geometrytype", spatial.NewGeometryType),
	sql.NewFunctionN("st_geohash", spatial.NewGeoHash),
	sql.NewFunctionN("st_geomfromgeojson", spatial.NewGeomFromGeoJSON),
	sql.NewFunctionN("st_geometryfromtext", spatial.NewGeomFromText),
	sql.NewFunctionN("st_geomfromtext", spatial.NewGeomFromText),
	sql.NewFunctionN("st_geometryfromwkb", spatial.NewGeomFromWKB),
	sql.NewFunctionN("st_geomfromwkb", spatial.NewGeomFromWKB),
	sql.NewFunction1("st_isclosed", spatial.NewIsClosed),
	sql.NewFunction2("st_interiorringn", spatial.NewInteriorRingN),
	sql.NewFunction2("st_intersects", spatial.NewIntersects),
	sql.NewFunction1("st_isempty", spatial.NewIsEmpty),
	sql.NewFunction1("st_issimple", spatial.NewIsSimple),
	sql.NewFunction1("st_latfromgeohash", spatial.NewLatFromGeoHash),
	sql.NewFunctionN("st_latitude", spatial.NewLatitude),
	sql.NewFunctionN("st_length", spatial.NewSTLength),
	sql.NewFunction1("st_longfromgeohash", spatial.NewLongFromGeoHash),
	sql.NewFunctionN("st_longitude", spatial.NewLongitude),
	sql.NewFunctionN("st_linefromtext", spatial.NewLineFromText),
	sql.NewFunctionN("st_linefromwkb", spatial.NewLineFromWKB),
	sql.NewFunctionN("st_linestringfromtext", spatial.NewLineFromText),
	sql.NewFunctionN("st_linestringfromwkb", spatial.NewLineFromWKB),
	sql.NewFunctionN("st_mlinefromtext", spatial.NewMLineFromText),
	sql.NewFunctionN("st_mlinefromwkb", spatial.NewMLineFromWKB),
	sql.NewFunctionN("st_multilinestringfromtext", spatial.NewMLineFromText),
	sql.NewFunctionN("st_multilinestringfromwkb", spatial.NewMLineFromWKB),
	sql.NewFunctionN("st_mpointfromtext", spatial.NewMPointFromText),
	sql.NewFunctionN("st_mpointfromwkb", spatial.NewMPointFromWKB),
	sql.NewFunctionN("st_multipointfromtext", spatial.NewMPointFromText),
	sql.NewFunctionN("st_multipointfromwkb", spatial.NewMPointFromWKB),
	sql.NewFunctionN("st_mpolyfromwkb", spatial.NewMPolyFromWKB),
	sql.NewFunctionN("st_mpolyfromtext", spatial.NewMPolyFromText),
	sql.NewFunctionN("st_multipolygonfromwkb", spatial.NewMPolyFromWKB),
	sql.NewFunctionN("st_multipolygonfromtext", spatial.NewMPolyFromText),
	sql.NewFunction1("st_numgeometries", spatial.NewNumGeometries),
	sql.NewFunction1("st_numinteriorring", spatial.NewNumInteriorRings),
	sql.NewFunction1("st_numinteriorrings", spatial.NewNumInteriorRings),
	sql.NewFunction1("st_numpoints", spatial.NewNumPoints),
	sql.NewFunctionN("st_perimeter", spatial.NewPerimeter),
	sql.NewFunction2("st_pointfromgeohash", spatial.NewPointFromGeoHash),
	sql.NewFunction2("st_pointn", spatial.NewPointN),
	sql.NewFunctionN("st_pointfromtext", spatial.NewPointFromText),
	sql.NewFunctionN("st_pointfromwkb", spatial.NewPointFromWKB),
	sql.NewFunctionN("st_polyfromtext", spatial.NewPolyFromText),
	sql.NewFunctionN("st_polyfromwkb", spatial.NewPolyFromWKB),
	sql.NewFunctionN("st_polygonfromtext", spatial.NewPolyFromText),
	sql.NewFunctionN("st_polygonfromwkb", spatial.NewPolyFromWKB),
	sql.NewFunctionN("st_srid", spatial.NewSRID),
	sql.NewFunction1("st_startpoint", spatial.NewStartPoint),
	sql.NewFunction1("st_swapxy", spatial.NewSwapXY),
	sql.NewFunction1("st_validate", spatial.NewValidate),
	sql.NewFunction2("st_within", spatial.NewWithin),
	sql.NewFunctionN("st_x", spatial.NewSTX),
	sql.NewFunctionN("st_y", spatial.NewSTY),
	sql.NewFunction2("strcmp", NewStrCmp),
	sql.NewFunctionN("substr", NewSubstring),
	sql.NewFunctionN("substring", NewSubstring),
	sql.NewFunction3("substring_index", NewSubstringIndex),
	sql.NewFunction1("sum", func(ctx *sql.Context, e sql.Expression) sql.Expression { return aggregation.NewSum(e) }),
	sql.NewFunction1("std", func(ctx *sql.Context, e sql.Expression) sql.Expression { return aggregation.NewStdDevPop(e) }),
	sql.NewFunction1("stddev", func(ctx *sql.Context, e sql.Expression) sql.Expression { return aggregation.NewStdDevPop(e) }),
	sql.NewFunction1("stddev_pop", func(ctx *sql.Context, e sql.Expression) sql.Expression { return aggregation.NewStdDevPop(e) }),
	sql.NewFunction1("stddev_samp", func(ctx *sql.Context, e sql.Expression) sql.Expression { return aggregation.NewStdDevSamp(e) }),
	sql.NewFunctionN("sysdate", NewSysdate),
	sql.NewFunction1("tan", NewTan),
	sql.NewFunction1("time", NewTime),
	sql.NewFunction2("time_format", NewTimeFormat),
	sql.NewFunction1("time_to_sec", NewTimeToSec),
	sql.NewFunction2("timediff", NewTimeDiff),
	sql.NewFunctionN("timestamp", NewDatetime),
	sql.NewFunction3("timestampdiff", NewTimestampDiff),
	sql.NewFunction1("to_base64", NewToBase64),
	sql.NewFunction1("to_days", NewToDays),
	sql.NewFunction1("ucase", NewUpper),
	sql.NewFunction1("uncompress", NewUncompress),
	sql.NewFunction1("uncompressed_length", NewUncompressedLength),
	sql.NewFunction1("unhex", NewUnhex),
	sql.NewFunctionN("unix_timestamp", NewUnixTimestamp),
	sql.NewFunction1("upper", NewUpper),
	sql.NewFunction0("user", NewUser),
	sql.NewFunctionN("utc_timestamp", NewUTCTimestamp),
	sql.NewFunction0("uuid", NewUUIDFunc),
	sql.NewFunction0("uuid_short", NewUUIDShortFunc),
	sql.NewFunctionN("uuid_to_bin", NewUUIDToBin),
	sql.NewFunction1("values", NewValues),
	sql.NewFunction1("validate_password_strength", NewValidatePasswordStrength),
	sql.NewFunction1("variance", func(ctx *sql.Context, e sql.Expression) sql.Expression { return aggregation.NewVarPop(e) }),
	sql.NewFunction1("var_pop", func(ctx *sql.Context, e sql.Expression) sql.Expression { return aggregation.NewVarPop(e) }),
	sql.NewFunction1("var_samp", func(ctx *sql.Context, e sql.Expression) sql.Expression { return aggregation.NewVarSamp(e) }),
	sql.NewFunction2("vec_distance", vector.NewL2SquaredDistance),
	sql.NewFunction2("vec_distance_l2_squared", vector.NewL2SquaredDistance),
	sql.NewFunction2("vec_distance_euclidean", vector.NewEuclideanDistance),
	sql.NewFunction2("vec_distance_cosine", vector.NewCosineDistance),
	sql.NewFunction2("vec_distance_inner_product", vector.NewInnerProductDistance),
	sql.NewFunction2("vec_distance_l1", vector.NewL1Distance),
	sql.NewFunctionN("distance", vector.NewGenericDistance),
	sql.NewFunction1("string_to_vector", vector.NewStringToVector),
	sql.NewFunction1("to_vector", vector.NewStringToVector),
	sql.NewFunction2("truncate", NewTruncate),
	sql.NewFunction1("vec_fromtext", vector.NewStringToVector),
	sql.NewFunction1("vector_to_string", vector.NewVectorToString),
	sql.NewFunction1("from_vector", vector.NewVectorToString),
	sql.NewFunction1("vec_totext", vector.NewVectorToString),
	sql.NewFunctionN("week", NewWeek),
	sql.NewFunction1("weekday", NewWeekday),
	sql.NewFunction1("weekofyear", NewWeekOfYear),
	sql.NewFunction1("year", NewYear),
	sql.NewFunctionN("yearweek", NewYearWeek),
}

func GetLockingFuncs(ctx *sql.Context, ls *sql.LockSubsystem) []sql.Function {
	return []sql.Function{
		sql.NewFunction2("get_lock", CreateNewGetLock(ctx, ls)),
		sql.NewFunction1("is_free_lock", NewIsFreeLock(ls)),
		sql.NewFunction1("is_used_lock", NewIsUsedLock(ls)),
		sql.NewFunction0("release_all_locks", NewReleaseAllLocks(ctx, ls)),
		sql.NewFunction1("release_lock", NewReleaseLock(ls)),
	}
}

// Registry is used to register functions
type Registry map[string]sql.Function

var _ sql.FunctionProvider = Registry{}

// NewRegistry creates a new Registry.
func NewRegistry() Registry {
	fr := make(Registry)
	fr.mustRegister(BuiltIns...)
	return fr
}

// Register registers functions, returning an error if it's already registered
func (r Registry) Register(fn ...sql.Function) error {
	for _, f := range fn {
		if _, ok := r[f.Name()]; ok {
			return ErrFunctionAlreadyRegistered.New(f.Name())
		}
		r[f.Name()] = f
	}
	return nil
}

// Function implements sql.FunctionProvider
func (r Registry) Function(ctx *sql.Context, schema, name string) (sql.Function, bool) {
	if fn, ok := r[name]; ok {
		return fn, true
	}
	return nil, false
}

func (r Registry) mustRegister(fn ...sql.Function) {
	if err := r.Register(fn...); err != nil {
		panic(err)
	}
}
