// Code generated by "stringer -type=JoinType -linecomment"; DO NOT EDIT.

package plan

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UnknownJoinType-0]
	_ = x[CrossJoinType-1]
	_ = x[InnerJoinType-2]
	_ = x[SemiJoinType-3]
	_ = x[AntiJoinType-4]
	_ = x[LeftJoinType-5]
	_ = x[FullOuterJoinType-6]
	_ = x[GroupByJoinType-7]
	_ = x[RightJoinType-8]
}

const _JoinType_name = "UnknownJoinTypeCrossJoinInnerJoinSemiJoinAntiJoinLeftJoinFullOuterJoinGroupByJoinRightJoin"

var _JoinType_index = [...]uint8{0, 15, 24, 33, 41, 49, 57, 70, 81, 90}

func (i JoinType) String() string {
	if i >= JoinType(len(_JoinType_index)-1) {
		return "JoinType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _JoinType_name[_JoinType_index[i]:_JoinType_index[i+1]]
}
