// Code generated by "stringer -type=indexScanOp -linecomment"; DO NOT EDIT.

package analyzer

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[indexScanOpEq-0]
	_ = x[indexScanOpNullSafeEq-1]
	_ = x[indexScanOpGt-2]
	_ = x[indexScanOpGte-3]
	_ = x[indexScanOpLt-4]
	_ = x[indexScanOpLte-5]
	_ = x[indexScanOpAnd-6]
	_ = x[indexScanOpOr-7]
	_ = x[indexScanOpIsNull-8]
	_ = x[indexScanOpIsNotNull-9]
}

const _indexScanOp_name = "=<=>>>=<<=&&||IS NULLIS NOT NULL"

var _indexScanOp_index = [...]uint8{0, 1, 4, 5, 7, 8, 10, 12, 14, 21, 32}

func (i indexScanOp) String() string {
	if i >= indexScanOp(len(_indexScanOp_index)-1) {
		return "indexScanOp(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _indexScanOp_name[_indexScanOp_index[i]:_indexScanOp_index[i+1]]
}
