// Code generated by "stringer -type=RuleId -linecomment"; DO NOT EDIT.

package analyzer

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[applyDefaultSelectLimitId-0]
	_ = x[validateOffsetAndLimitId-1]
	_ = x[validateStarExpressionsId-2]
	_ = x[validateCreateTableId-3]
	_ = x[validateAlterTableId-4]
	_ = x[validateExprSemId-5]
	_ = x[loadStoredProceduresId-6]
	_ = x[validateDropTablesId-7]
	_ = x[resolveDropConstraintId-8]
	_ = x[validateDropConstraintId-9]
	_ = x[resolveCreateSelectId-10]
	_ = x[resolveSubqueriesId-11]
	_ = x[resolveUnionsId-12]
	_ = x[ValidateColumnDefaultsId-13]
	_ = x[validateCreateTriggerId-14]
	_ = x[validateCreateProcedureId-15]
	_ = x[validateReadOnlyDatabaseId-16]
	_ = x[validateReadOnlyTransactionId-17]
	_ = x[validateDatabaseSetId-18]
	_ = x[validatePrivilegesId-19]
	_ = x[applyEventSchedulerId-20]
	_ = x[flattenTableAliasesId-21]
	_ = x[pushdownSubqueryAliasFiltersId-22]
	_ = x[validateCheckConstraintId-23]
	_ = x[replaceCountStarId-24]
	_ = x[replaceCrossJoinsId-25]
	_ = x[moveJoinCondsToFilterId-26]
	_ = x[simplifyFiltersId-27]
	_ = x[pushNotFiltersId-28]
	_ = x[hoistOutOfScopeFiltersId-29]
	_ = x[unnestInSubqueriesId-30]
	_ = x[unnestExistsSubqueriesId-31]
	_ = x[finalizeSubqueriesId-32]
	_ = x[finalizeUnionsId-33]
	_ = x[loadTriggersId-34]
	_ = x[processTruncateId-35]
	_ = x[resolveAlterColumnId-36]
	_ = x[stripTableNameInDefaultsId-37]
	_ = x[optimizeJoinsId-38]
	_ = x[pushFiltersId-39]
	_ = x[applyIndexesFromOuterScopeId-40]
	_ = x[pruneTablesId-41]
	_ = x[assignExecIndexesId-42]
	_ = x[inlineSubqueryAliasRefsId-43]
	_ = x[eraseProjectionId-44]
	_ = x[flattenDistinctId-45]
	_ = x[replaceAggId-46]
	_ = x[replaceIdxSortId-47]
	_ = x[insertTopNId-48]
	_ = x[replaceIdxOrderByDistanceId-49]
	_ = x[applyHashInId-50]
	_ = x[resolveInsertRowsId-51]
	_ = x[applyTriggersId-52]
	_ = x[applyProceduresId-53]
	_ = x[assignRoutinesId-54]
	_ = x[modifyUpdateExprsForJoinId-55]
	_ = x[applyUpdateAccumulatorsId-56]
	_ = x[applyForeignKeysId-57]
	_ = x[validateResolvedId-58]
	_ = x[validateOrderById-59]
	_ = x[validateGroupById-60]
	_ = x[validateSchemaSourceId-61]
	_ = x[validateIndexCreationId-62]
	_ = x[ValidateOperandsId-63]
	_ = x[validateIntervalUsageId-64]
	_ = x[validateSubqueryColumnsId-65]
	_ = x[validateUnionSchemasMatchId-66]
	_ = x[validateAggregationsId-67]
	_ = x[validateDeleteFromId-68]
	_ = x[cacheSubqueryAliasesInJoinsId-69]
	_ = x[BacktickDefaulColumnValueNamesId-70]
	_ = x[TrackProcessId-71]
}

const _RuleId_name = "applyDefaultSelectLimitvalidateOffsetAndLimitvalidateStarExpressionsvalidateCreateTablevalidateAlterTablevalidateExprSemloadStoredProceduresvalidateDropTablesresolveDropConstraintvalidateDropConstraintresolveCreateSelectresolveSubqueriesresolveUnionsvalidateColumnDefaultsvalidateCreateTriggervalidateCreateProcedurevalidateReadOnlyDatabasevalidateReadOnlyTransactionvalidateDatabaseSetvalidatePrivilegesapplyEventSchedulerflattenTableAliasespushdownSubqueryAliasFiltersvalidateCheckConstraintsreplaceCountStarreplaceCrossJoinsmoveJoinConditionsToFiltersimplifyFilterspushNotFiltershoistOutOfScopeFiltersunnestInSubqueriesunnestExistsSubqueriesfinalizeSubqueriesfinalizeUnionsloadTriggersprocessTruncateresolveAlterColumnstripTableNamesFromColumnDefaultsoptimizeJoinspushFiltersapplyIndexesFromOuterScopepruneTablesassignExecIndexesinlineSubqueryAliasRefseraseProjectionflattenDistinctreplaceAggreplaceIdxSortinsertTopNNodesreplaceIdxOrderByDistanceapplyHashInresolveInsertRowsapplyTriggersapplyProceduresassignRoutinesmodifyUpdateExprsForJoinapplyUpdateAccumulatorsapplyForeignKeysvalidateResolvedvalidateOrderByvalidateGroupByvalidateSchemaSourcevalidateIndexCreationvalidateOperandsvalidateIntervalUsagevalidateSubqueryColumnsvalidateUnionSchemasMatchvalidateAggregationsvalidateDeleteFromcacheSubqueryAliasesInJoinsbacktickDefaultColumnValueNamestrackProcess"

var _RuleId_index = [...]uint16{0, 23, 45, 68, 87, 105, 120, 140, 158, 179, 201, 220, 237, 250, 272, 293, 316, 340, 367, 386, 404, 423, 442, 470, 494, 510, 527, 553, 568, 582, 604, 622, 644, 662, 676, 688, 703, 721, 754, 767, 778, 804, 815, 832, 855, 870, 885, 895, 909, 924, 949, 960, 977, 990, 1005, 1019, 1043, 1066, 1082, 1098, 1113, 1128, 1148, 1169, 1185, 1206, 1229, 1254, 1274, 1292, 1319, 1350, 1362}

func (i RuleId) String() string {
	if i < 0 || i >= RuleId(len(_RuleId_index)-1) {
		return "RuleId(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _RuleId_name[_RuleId_index[i]:_RuleId_index[i+1]]
}
