name: Test Server Engine
on: [pull_request]

concurrency:
  group: server-engine-test-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.20.x]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Test using Server Engine
        if: ${{ matrix.platform == 'ubuntu-latest' }}
        run: go test ./...
        env:
          CI_TEST: "true"
          SERVER_ENGINE_TEST: "true"
      - name: Test using Server Engine
        if: ${{ matrix.platform == 'ubuntu-latest' }}
        run: go test -race ./...
        env:
          CI_TEST: "true"
          SERVER_ENGINE_TEST: "true"
